const japaneseWords1 = [
  { romanji: 'watashi', answer: 'I/me' },
  { romanji: 'anata', answer: 'you' },
  { romanji: 'kare', answer: 'he/him' },
  { romanji: 'kanojo', answer: 'she/her' },
  { romanji: 'sensei', answer: 'teacher' },
  { romanji: 'gakkou', answer: 'school' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'hon', answer: 'book' },
  { romanji: 'mizu', answer: 'water' },
  { romanji: 'ocha', answer: 'tea' },
  { romanji: 'gohan', answer: 'rice/meal' },
  { romanji: 'tabemono', answer: 'food' },
  { romanji: 'nomimono', answer: 'drink' },
  { romanji: 'kuruma', answer: 'car' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'kooen', answer: 'park' },
  { romanji: 'machi', answer: 'town/city' },
  { romanji: 'ie', answer: 'house/home' },
  { romanji: 'heya', answer: 'room' },
  { romanji: 'doa', answer: 'door' },
  { romanji: 'mado', answer: 'window' },
  { romanji: 'isu', answer: 'chair' },
  { romanji: 'teburu', answer: 'table' },
  { romanji: 'denki', answer: 'electricity/light' },
  { romanji: 'denwa', answer: 'telephone' },
  { romanji: 'kamera', answer: 'camera' },
  { romanji: 'jisho', answer: 'dictionary' },
  { romanji: 'pen', answer: 'pen' },
  { romanji: 'enpitsu', answer: 'pencil' },
  { romanji: 'kami', answer: 'paper' },
  { romanji: 'honya', answer: 'bookstore' },
  { romanji: 'kissaten', answer: 'cafe' },
  { romanji: 'resutoran', answer: 'restaurant' },
  { romanji: 'omise', answer: 'shop/store' },
  { romanji: 'shigoto', answer: 'work/job' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'kaimono', answer: 'shopping' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'tabi', answer: 'trip/journey' },
  { romanji: 'tenki', answer: 'weather' },
  { romanji: 'ame', answer: 'rain' },
  { romanji: 'yuki', answer: 'snow' },
  { romanji: 'kaze', answer: 'wind' },
  { romanji: 'taiyou', answer: 'sun' },
  { romanji: 'tsuki', answer: 'moon' },
  { romanji: 'hoshi', answer: 'star' },
  { romanji: 'umi', answer: 'sea/ocean' },
  { romanji: 'kawa', answer: 'river' },
  { romanji: 'yama', answer: 'mountain' },
  { romanji: 'mori', answer: 'forest' },
  { romanji: 'hana', answer: 'flower' },
  { romanji: 'ki', answer: 'tree' },
  { romanji: 'tori', answer: 'bird' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'niku', answer: 'meat' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'pan', answer: 'bread' },
  { romanji: 'miruku', answer: 'milk' },
  { romanji: 'kouhii', answer: 'coffee' },
  { romanji: 'supootsu', answer: 'sports' },
  { romanji: 'sakkaa', answer: 'soccer' },
  { romanji: 'basukettobooru', answer: 'basketball' },
  { romanji: 'tenisu', answer: 'tennis' },
  { romanji: 'yakyuu', answer: 'baseball' },
  { romanji: 'ongaku', answer: 'music' },
  { romanji: 'uta', answer: 'song' },
  { romanji: 'gitaa', answer: 'guitar' },
  { romanji: 'piano', answer: 'piano' },
  { romanji: 'eiga', answer: 'movie' },
  { romanji: 'terebi', answer: 'TV' },
  { romanji: 'denshiRenji', answer: 'microwave' },
  { romanji: 'reizouko', answer: 'refrigerator' },
  { romanji: 'kagi', answer: 'key' },
  { romanji: 'kasa', answer: 'umbrella' },
  { romanji: 'fuku', answer: 'clothes' },
  { romanji: 'shatsu', answer: 'shirt' },
  { romanji: 'zubon', answer: 'pants' },
  { romanji: 'kutsu', answer: 'shoes' },
  { romanji: 'kaban', answer: 'bag' },
  { romanji: 'meishi', answer: 'business card' },
  { romanji: 'tegami', answer: 'letter' },
  { romanji: 'himo', answer: 'string/cord' },
  { romanji: 'hashi', answer: 'chopsticks' },
  { romanji: 'futon', answer: 'futon/bed' },
  { romanji: 'atama', answer: 'head' },
  { romanji: 'karada', answer: 'body' },
  { romanji: 'ai', answer: 'love' },
  { romanji: 'yume', answer: 'dream' },
  { romanji: 'kimochi', answer: 'feeling' },
  { romanji: 'shiawase', answer: 'happiness' },
  { romanji: 'kanashimi', answer: 'sadness' },
  { romanji: 'okoru', answer: 'anger' },
  { romanji: 'nervousu', answer: 'nervous' },
  { romanji: 'tanoshii', answer: 'fun/enjoyable' },
  { romanji: 'omoshiroi', answer: 'interesting' },
  { romanji: 'tsukareta', answer: 'tired' },
  { romanji: 'byouki', answer: 'sickness' },
  { romanji: 'kusuri', answer: 'medicine' },
  { romanji: 'ishya', answer: 'doctor' },
  { romanji: 'kaigo', answer: 'nursing/care' },
  { romanji: 'byouin', answer: 'hospital' },
  { romanji: 'kaze', answer: 'cold (illness)' },
  { romanji: 'sushi', answer: 'sushi' },
  { romanji: 'ramen', answer: 'ramen' },
  { romanji: 'udon', answer: 'udon noodles' },
  { romanji: 'soba', answer: 'soba noodles' },
  { romanji: 'tempura', answer: 'tempura' },
  { romanji: 'okonomiyaki', answer: 'savory pancake' },
  { romanji: 'takoyaki', answer: 'octopus balls' },
  { romanji: 'yakiniku', answer: 'grilled meat' },
  { romanji: 'tonkatsu', answer: 'pork cutlet' },
  { romanji: 'karaage', answer: 'fried chicken' },
  { romanji: 'gyoza', answer: 'dumplings' },
  { romanji: 'miso', answer: 'miso' },
  { romanji: 'tofu', answer: 'tofu' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'yasai', answer: 'vegetable' },
  { romanji: 'kudamono', answer: 'fruit' },
  { romanji: 'ringo', answer: 'apple' },
  { romanji: 'mikan', answer: 'mandarin orange' },
  { romanji: 'banana', answer: 'banana' },
  { romanji: 'budou', answer: 'grapes' },
  { romanji: 'ichigo', answer: 'strawberry' },
  { romanji: 'suika', answer: 'watermelon' },
  { romanji: 'melon', answer: 'melon' },
  { romanji: 'nashi', answer: 'pear' },
  { romanji: 'kaki', answer: 'persimmon' },
  { romanji: 'ume', answer: 'plum' },
  { romanji: 'yamaimo', answer: 'mountain yam' },
  { romanji: 'jagaimo', answer: 'potato' },
  { romanji: 'ninjin', answer: 'carrot' },
  { romanji: 'tamanegi', answer: 'onion' },
  { romanji: 'kyuuri', answer: 'cucumber' },
  { romanji: 'nasu', answer: 'eggplant' },
  { romanji: 'tomato', answer: 'tomato' },
  { romanji: 'retasu', answer: 'lettuce' },
  { romanji: 'horenso', answer: 'spinach' },
  { romanji: 'pīman', answer: 'bell pepper' },
  { romanji: 'cabbage', answer: 'cabbage' },
  { romanji: 'hakusai', answer: 'Chinese cabbage' },
  { romanji: 'kyabetsu', answer: 'cabbage' },
  { romanji: 'gohan', answer: 'cooked rice' },
  { romanji: 'okazu', answer: 'side dish' },
  { romanji: 'misoshiru', answer: 'miso soup' },
  { romanji: 'sashimi', answer: 'sashimi' },
  { romanji: 'nabe', answer: 'hot pot' },
  { romanji: 'oden', answer: 'oden' },
  { romanji: 'takikomi gohan', answer: 'seasoned rice' },
  { romanji: 'onigiri', answer: 'rice ball' },
  { romanji: 'tamago yaki', answer: 'rolled omelette' },
  { romanji: 'shoyu', answer: 'soy sauce' },
  { romanji: 'sukiyaki', answer: 'sukiyaki' },
  { romanji: 'yakitori', answer: 'grilled chicken skewer' },
  { romanji: 'okashi', answer: 'sweets/snacks' },
  { romanji: 'kashi', answer: 'sweets' },
  { romanji: 'ame', answer: 'candy' },
  { romanji: 'choco', answer: 'chocolate' },
  { romanji: 'keeki', answer: 'cake' },
  { romanji: 'aisu kuriimu', answer: 'ice cream' },
  { romanji: 'bijinesu', answer: 'business' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'shacho', answer: 'company president' },
  { romanji: 'kacho', answer: 'section chief' },
  { romanji: 'bucho', answer: 'department head' },
  { romanji: 'kaikei', answer: 'accounting' },
  { romanji: 'jimu', answer: 'office' },
  { romanji: 'jimushitsu', answer: 'office room' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'shinkansen', answer: 'bullet train' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'kuko', answer: 'airport' },
  { romanji: 'takushi', answer: 'taxi' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'noriba', answer: 'bus stop' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'shachou', answer: 'company president' },
  { romanji: 'kaishain', answer: 'company employee' },
  { romanji: 'hisho', answer: 'secretary' },
  { romanji: 'tenin', answer: 'shop clerk' },
  { romanji: 'isya', answer: 'doctor' },
  { romanji: 'kangofu', answer: 'nurse' },
  { romanji: 'sensei', answer: 'teacher' },
  { romanji: 'gakusei', answer: 'student' },
  { romanji: 'koukousei', answer: 'high school student' },
  { romanji: 'chuugakusei', answer: 'middle school student' },
  { romanji: 'shougakusei', answer: 'elementary student' },
  { romanji: 'okasan', answer: 'mother' },
  { romanji: 'otosan', answer: 'father' },
  { romanji: 'onisan', answer: 'older brother' },
  { romanji: 'oneesan', answer: 'older sister' },
  { romanji: 'imouto', answer: 'younger sister' },
  { romanji: 'otouto', answer: 'younger brother' },
  { romanji: 'sofu', answer: 'grandfather' },
  { romanji: 'sobo', answer: 'grandmother' },
  { romanji: 'kodomo', answer: 'child' },
  { romanji: 'tomodachi', answer: 'friend' },
  { romanji: 'kareshi', answer: 'boyfriend' },
  { romanji: 'kanojo', answer: 'girlfriend' },
  { romanji: 'kazoku', answer: 'family' },
  { romanji: 'kekkon', answer: 'marriage' },
  { romanji: 'shigoto', answer: 'job/work' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'tenpo', answer: 'store/shop' },
  { romanji: 'shokugyou', answer: 'occupation' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'kuruma', answer: 'car' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'tabemono', answer: 'food' },
  { romanji: 'nomimono', answer: 'drink' },
  { romanji: 'gohan', answer: 'rice/meal' },
  { romanji: 'pan', answer: 'bread' },
  { romanji: 'niku', answer: 'meat' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'yasai', answer: 'vegetable' },
  { romanji: 'kudamono', answer: 'fruit' },
  { romanji: 'mizu', answer: 'water' },
  { romanji: 'ocha', answer: 'tea' },
  { romanji: 'kouhii', answer: 'coffee' },
  { romanji: 'miruku', answer: 'milk' }
];

const japaneseWords2 = [
  { romanji: 'sūpu', answer: 'soup' },
  { romanji: 'misoshiru', answer: 'miso soup' },
  { romanji: 'salada', answer: 'salad' },
  { romanji: 'sakana no saku', answer: 'grilled fish' },
  { romanji: 'niku no yaki', answer: 'grilled meat' },
  { romanji: 'gyoza', answer: 'dumplings' },
  { romanji: 'karaage', answer: 'fried chicken' },
  { romanji: 'tonkatsu', answer: 'pork cutlet' },
  { romanji: 'yakitori', answer: 'chicken skewer' },
  { romanji: 'okonomiyaki', answer: 'savory pancake' },
  { romanji: 'takoyaki', answer: 'octopus balls' },
  { romanji: 'ramen', answer: 'ramen' },
  { romanji: 'udon', answer: 'udon noodles' },
  { romanji: 'soba', answer: 'soba noodles' },
  { romanji: 'onigiri', answer: 'rice ball' },
  { romanji: 'tamago yaki', answer: 'rolled omelette' },
  { romanji: 'tofu', answer: 'tofu' },
  { romanji: 'shoyu', answer: 'soy sauce' },
  { romanji: 'sukiyaki', answer: 'sukiyaki' },
  { romanji: 'nabe', answer: 'hot pot' },
  { romanji: 'oden', answer: 'oden' },
  { romanji: 'takikomi gohan', answer: 'seasoned rice' },
  { romanji: 'kome', answer: 'rice (uncooked)' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'gyuunyuu', answer: 'milk' },
  { romanji: 'miruku', answer: 'milk' },
  { romanji: 'kouhii', answer: 'coffee' },
  { romanji: 'ocha', answer: 'tea' },
  { romanji: 'kōra', answer: 'cola' },
  { romanji: 'jūsu', answer: 'juice' },
  { romanji: 'mizu', answer: 'water' },
  { romanji: 'nomimono', answer: 'drink' },
  { romanji: 'tabemono', answer: 'food' },
  { romanji: 'yasai', answer: 'vegetable' },
  { romanji: 'kudamono', answer: 'fruit' },
  { romanji: 'ringo', answer: 'apple' },
  { romanji: 'mikan', answer: 'mandarin' },
  { romanji: 'banana', answer: 'banana' },
  { romanji: 'budou', answer: 'grape' },
  { romanji: 'ichigo', answer: 'strawberry' },
  { romanji: 'suika', answer: 'watermelon' },
  { romanji: 'melon', answer: 'melon' },
  { romanji: 'nashi', answer: 'pear' },
  { romanji: 'kaki', answer: 'persimmon' },
  { romanji: 'ume', answer: 'plum' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'niku', answer: 'meat' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'porku', answer: 'pork' },
  { romanji: 'chikin', answer: 'chicken' },
  { romanji: 'gyuuniku', answer: 'beef' },
  { romanji: 'tonkatsu', answer: 'pork cutlet' },
  { romanji: 'karaage', answer: 'fried chicken' },
  { romanji: 'yakiniku', answer: 'grilled meat' },
  { romanji: 'sashimi', answer: 'sashimi' },
  { romanji: 'sushi', answer: 'sushi' },
  { romanji: 'okashi', answer: 'sweets/snacks' },
  { romanji: 'ame', answer: 'candy' },
  { romanji: 'choko', answer: 'chocolate' },
  { romanji: 'keeki', answer: 'cake' },
  { romanji: 'aisu kuriimu', answer: 'ice cream' },
  { romanji: 'bijinesu', answer: 'business' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'shacho', answer: 'president' },
  { romanji: 'kacho', answer: 'section chief' },
  { romanji: 'bucho', answer: 'department head' },
  { romanji: 'kaikei', answer: 'accounting' },
  { romanji: 'jimu', answer: 'office' },
  { romanji: 'jimushitsu', answer: 'office room' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'shinkansen', answer: 'bullet train' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'kuko', answer: 'airport' },
  { romanji: 'takushi', answer: 'taxi' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'noriba', answer: 'bus stop' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'shachou', answer: 'company president' },
  { romanji: 'kaishain', answer: 'company employee' },
  { romanji: 'hisho', answer: 'secretary' },
  { romanji: 'tenin', answer: 'shop clerk' },
  { romanji: 'isya', answer: 'doctor' },
  { romanji: 'kangofu', answer: 'nurse' },
  { romanji: 'sensei', answer: 'teacher' },
  { romanji: 'gakusei', answer: 'student' },
  { romanji: 'koukousei', answer: 'high school student' },
  { romanji: 'chuugakusei', answer: 'middle school student' },
  { romanji: 'shougakusei', answer: 'elementary student' },
  { romanji: 'okasan', answer: 'mother' },
  { romanji: 'otosan', answer: 'father' },
  { romanji: 'onisan', answer: 'older brother' },
  { romanji: 'oneesan', answer: 'older sister' },
  { romanji: 'imouto', answer: 'younger sister' },
  { romanji: 'otouto', answer: 'younger brother' },
  { romanji: 'sofu', answer: 'grandfather' },
  { romanji: 'sobo', answer: 'grandmother' },
  { romanji: 'kodomo', answer: 'child' },
  { romanji: 'tomodachi', answer: 'friend' },
  { romanji: 'kareshi', answer: 'boyfriend' },
  { romanji: 'kanojo', answer: 'girlfriend' },
  { romanji: 'kazoku', answer: 'family' },
  { romanji: 'kekkon', answer: 'marriage' },
  { romanji: 'shigoto', answer: 'job/work' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'tenpo', answer: 'store/shop' },
  { romanji: 'shokugyou', answer: 'occupation' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'kuruma', answer: 'car' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'shachou', answer: 'company president' },
  { romanji: 'kaishain', answer: 'company employee' },
  { romanji: 'hisho', answer: 'secretary' },
  { romanji: 'tenin', answer: 'shop clerk' },
  { romanji: 'isya', answer: 'doctor' },
  { romanji: 'kangofu', answer: 'nurse' },
  { romanji: 'sensei', answer: 'teacher' },
  { romanji: 'gakusei', answer: 'student' },
  { romanji: 'koukousei', answer: 'high school student' },
  { romanji: 'chuugakusei', answer: 'middle school student' },
  { romanji: 'shougakusei', answer: 'elementary student' },
  { romanji: 'okasan', answer: 'mother' },
  { romanji: 'otosan', answer: 'father' },
  { romanji: 'onisan', answer: 'older brother' },
  { romanji: 'oneesan', answer: 'older sister' },
  { romanji: 'imouto', answer: 'younger sister' },
  { romanji: 'otouto', answer: 'younger brother' },
  { romanji: 'sofu', answer: 'grandfather' },
  { romanji: 'sobo', answer: 'grandmother' },
  { romanji: 'kodomo', answer: 'child' },
  { romanji: 'tomodachi', answer: 'friend' },
  { romanji: 'kareshi', answer: 'boyfriend' },
  { romanji: 'kanojo', answer: 'girlfriend' },
  { romanji: 'kazoku', answer: 'family' }
];


const japaneseWords3 = [
  { romanji: 'heya', answer: 'room' },
  { romanji: 'ie', answer: 'house' },
  { romanji: 'mado', answer: 'window' },
  { romanji: 'doa', answer: 'door' },
  { romanji: 'isu', answer: 'chair' },
  { romanji: 'teburu', answer: 'table' },
  { romanji: 'beddo', answer: 'bed' },
  { romanji: 'makura', answer: 'pillow' },
  { romanji: 'futon', answer: 'futon' },
  { romanji: 'denki', answer: 'electricity/light' },
  { romanji: 'terebi', answer: 'TV' },
  { romanji: 'denshi renji', answer: 'microwave' },
  { romanji: 'reizouko', answer: 'refrigerator' },
  { romanji: 'kagi', answer: 'key' },
  { romanji: 'kasa', answer: 'umbrella' },
  { romanji: 'fuku', answer: 'clothes' },
  { romanji: 'shatsu', answer: 'shirt' },
  { romanji: 'zubon', answer: 'pants' },
  { romanji: 'kutsu', answer: 'shoes' },
  { romanji: 'kaban', answer: 'bag' },
  { romanji: 'meishi', answer: 'business card' },
  { romanji: 'tegami', answer: 'letter' },
  { romanji: 'himo', answer: 'string/cord' },
  { romanji: 'hashi', answer: 'chopsticks' },
  { romanji: 'purezento', answer: 'present/gift' },
  { romanji: 'kuruma', answer: 'car' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'shinkansen', answer: 'bullet train' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'kuko', answer: 'airport' },
  { romanji: 'takushi', answer: 'taxi' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'noriba', answer: 'bus stop' },
  { romanji: 'michi', answer: 'road' },
  { romanji: 'hashi', answer: 'bridge' },
  { romanji: 'kuni', answer: 'country' },
  { romanji: 'machi', answer: 'town/city' },
  { romanji: 'shima', answer: 'island' },
  { romanji: 'oka', answer: 'hill' },
  { romanji: 'yama', answer: 'mountain' },
  { romanji: 'kawa', answer: 'river' },
  { romanji: 'umi', answer: 'sea/ocean' },
  { romanji: 'mori', answer: 'forest' },
  { romanji: 'hana', answer: 'flower' },
  { romanji: 'ki', answer: 'tree' },
  { romanji: 'tori', answer: 'bird' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'uma', answer: 'horse' },
  { romanji: 'ushi', answer: 'cow' },
  { romanji: 'butaniku', answer: 'pork' },
  { romanji: 'chikin', answer: 'chicken' },
  { romanji: 'gyuuniku', answer: 'beef' },
  { romanji: 'tamago', answer: 'egg' },
  { romanji: 'pan', answer: 'bread' },
  { romanji: 'gohan', answer: 'rice/meal' },
  { romanji: 'yasai', answer: 'vegetable' },
  { romanji: 'kudamono', answer: 'fruit' },
  { romanji: 'ringo', answer: 'apple' },
  { romanji: 'mikan', answer: 'mandarin orange' },
  { romanji: 'banana', answer: 'banana' },
  { romanji: 'budou', answer: 'grapes' },
  { romanji: 'ichigo', answer: 'strawberry' },
  { romanji: 'suika', answer: 'watermelon' },
  { romanji: 'melon', answer: 'melon' },
  { romanji: 'nashi', answer: 'pear' },
  { romanji: 'kaki', answer: 'persimmon' },
  { romanji: 'ume', answer: 'plum' },
  { romanji: 'yasai', answer: 'vegetable' },
  { romanji: 'ninjin', answer: 'carrot' },
  { romanji: 'tamanegi', answer: 'onion' },
  { romanji: 'kyuuri', answer: 'cucumber' },
  { romanji: 'nasu', answer: 'eggplant' },
  { romanji: 'tomato', answer: 'tomato' },
  { romanji: 'retasu', answer: 'lettuce' },
  { romanji: 'horenso', answer: 'spinach' },
  { romanji: 'pīman', answer: 'bell pepper' },
  { romanji: 'kyabetsu', answer: 'cabbage' },
  { romanji: 'hakusai', answer: 'Chinese cabbage' },
  { romanji: 'tabemono', answer: 'food' },
  { romanji: 'nomimono', answer: 'drink' },
  { romanji: 'mizu', answer: 'water' },
  { romanji: 'ocha', answer: 'tea' },
  { romanji: 'kouhii', answer: 'coffee' },
  { romanji: 'miruku', answer: 'milk' },
  { romanji: 'sūpu', answer: 'soup' },
  { romanji: 'misoshiru', answer: 'miso soup' },
  { romanji: 'salada', answer: 'salad' },
  { romanji: 'gyoza', answer: 'dumplings' },
  { romanji: 'karaage', answer: 'fried chicken' },
  { romanji: 'tonkatsu', answer: 'pork cutlet' },
  { romanji: 'yakitori', answer: 'chicken skewer' },
  { romanji: 'okonomiyaki', answer: 'savory pancake' },
  { romanji: 'takoyaki', answer: 'octopus balls' },
  { romanji: 'ramen', answer: 'ramen' },
  { romanji: 'udon', answer: 'udon noodles' },
  { romanji: 'soba', answer: 'soba noodles' },
  { romanji: 'sushi', answer: 'sushi' },
  { romanji: 'sashimi', answer: 'sashimi' },
  { romanji: 'okashi', answer: 'sweets/snacks' },
  { romanji: 'ame', answer: 'candy' },
  { romanji: 'choko', answer: 'chocolate' },
  { romanji: 'keeki', answer: 'cake' },
  { romanji: 'aisu kuriimu', answer: 'ice cream' },
  { romanji: 'bijinesu', answer: 'business' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'shacho', answer: 'president' },
  { romanji: 'kacho', answer: 'section chief' },
  { romanji: 'bucho', answer: 'department head' },
  { romanji: 'kaikei', answer: 'accounting' },
  { romanji: 'jimu', answer: 'office' },
  { romanji: 'jimushitsu', answer: 'office room' },
  { romanji: 'shigoto', answer: 'job/work' },
  { romanji: 'shokugyou', answer: 'occupation' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'tenki', answer: 'weather' },
  { romanji: 'ame', answer: 'rain' },
  { romanji: 'yuki', answer: 'snow' },
  { romanji: 'kaze', answer: 'wind' },
  { romanji: 'taiyou', answer: 'sun' },
  { romanji: 'tsuki', answer: 'moon' },
  { romanji: 'hoshi', answer: 'star' },
  { romanji: 'umi', answer: 'sea/ocean' },
  { romanji: 'kawa', answer: 'river' },
  { romanji: 'yama', answer: 'mountain' },
  { romanji: 'mori', answer: 'forest' },
  { romanji: 'hana', answer: 'flower' },
  { romanji: 'ki', answer: 'tree' },
  { romanji: 'tori', answer: 'bird' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'uma', answer: 'horse' },
  { romanji: 'ushi', answer: 'cow' },
  { romanji: 'choucho', answer: 'butterfly' },
  { romanji: 'ari', answer: 'ant' },
  { romanji: 'kani', answer: 'crab' },
  { romanji: 'ebi', answer: 'shrimp' },
  { romanji: 'kame', answer: 'turtle' },
  { romanji: 'kaeru', answer: 'frog' },
  { romanji: 'saru', answer: 'monkey' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'heya', answer: 'room' },
  { romanji: 'ie', answer: 'house' },
  { romanji: 'mado', answer: 'window' },
  { romanji: 'doa', answer: 'door' },
  { romanji: 'isu', answer: 'chair' },
  { romanji: 'teburu', answer: 'table' },
  { romanji: 'beddo', answer: 'bed' },
  { romanji: 'makura', answer: 'pillow' }
];


const japaneseWords4 = [
  { romanji: 'futon', answer: 'futon' },
  { romanji: 'denki', answer: 'electricity/light' },
  { romanji: 'terebi', answer: 'TV' },
  { romanji: 'reizouko', answer: 'refrigerator' },
  { romanji: 'denshi renji', answer: 'microwave' },
  { romanji: 'kagi', answer: 'key' },
  { romanji: 'kasa', answer: 'umbrella' },
  { romanji: 'fuku', answer: 'clothes' },
  { romanji: 'shatsu', answer: 'shirt' },
  { romanji: 'zubon', answer: 'pants' },
  { romanji: 'kutsu', answer: 'shoes' },
  { romanji: 'kaban', answer: 'bag' },
  { romanji: 'meishi', answer: 'business card' },
  { romanji: 'tegami', answer: 'letter' },
  { romanji: 'himo', answer: 'string/cord' },
  { romanji: 'hashi', answer: 'chopsticks' },
  { romanji: 'purezento', answer: 'present/gift' },
  { romanji: 'kuruma', answer: 'car' },
  { romanji: 'jitensha', answer: 'bicycle' },
  { romanji: 'densha', answer: 'train' },
  { romanji: 'eki', answer: 'station' },
  { romanji: 'shinkansen', answer: 'bullet train' },
  { romanji: 'hikouki', answer: 'airplane' },
  { romanji: 'kuko', answer: 'airport' },
  { romanji: 'takushi', answer: 'taxi' },
  { romanji: 'basu', answer: 'bus' },
  { romanji: 'noriba', answer: 'bus stop' },
  { romanji: 'michi', answer: 'road' },
  { romanji: 'hashi', answer: 'bridge' },
  { romanji: 'kuni', answer: 'country' },
  { romanji: 'machi', answer: 'town/city' },
  { romanji: 'shima', answer: 'island' },
  { romanji: 'oka', answer: 'hill' },
  { romanji: 'yama', answer: 'mountain' },
  { romanji: 'kawa', answer: 'river' },
  { romanji: 'umi', answer: 'sea/ocean' },
  { romanji: 'mori', answer: 'forest' },
  { romanji: 'hana', answer: 'flower' },
  { romanji: 'ki', answer: 'tree' },
  { romanji: 'tori', answer: 'bird' },
  { romanji: 'sakana', answer: 'fish' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'uma', answer: 'horse' },
  { romanji: 'ushi', answer: 'cow' },
  { romanji: 'choucho', answer: 'butterfly' },
  { romanji: 'ari', answer: 'ant' },
  { romanji: 'kani', answer: 'crab' },
  { romanji: 'ebi', answer: 'shrimp' },
  { romanji: 'kame', answer: 'turtle' },
  { romanji: 'kaeru', answer: 'frog' },
  { romanji: 'saru', answer: 'monkey' },
  { romanji: 'kumo', answer: 'spider/cloud' },
  { romanji: 'neko', answer: 'cat' },
  { romanji: 'inu', answer: 'dog' },
  { romanji: 'heya', answer: 'room' },
  { romanji: 'ie', answer: 'house' },
  { romanji: 'mado', answer: 'window' },
  { romanji: 'doa', answer: 'door' },
  { romanji: 'isu', answer: 'chair' },
  { romanji: 'teburu', answer: 'table' },
  { romanji: 'beddo', answer: 'bed' },
  { romanji: 'makura', answer: 'pillow' },
  { romanji: 'futon', answer: 'futon' },
  { romanji: 'denki', answer: 'electricity/light' },
  { romanji: 'terebi', answer: 'TV' },
  { romanji: 'reizouko', answer: 'refrigerator' },
  { romanji: 'denshi renji', answer: 'microwave' },
  { romanji: 'kagi', answer: 'key' },
  { romanji: 'kasa', answer: 'umbrella' },
  { romanji: 'fuku', answer: 'clothes' },
  { romanji: 'shatsu', answer: 'shirt' },
  { romanji: 'zubon', answer: 'pants' },
  { romanji: 'kutsu', answer: 'shoes' },
  { romanji: 'kaban', answer: 'bag' },
  { romanji: 'meishi', answer: 'business card' },
  { romanji: 'tegami', answer: 'letter' },
  { romanji: 'himo', answer: 'string/cord' },
  { romanji: 'hashi', answer: 'chopsticks' },
  { romanji: 'purezento', answer: 'present/gift' },
  { romanji: 'shigoto', answer: 'job/work' },
  { romanji: 'shokugyou', answer: 'occupation' },
  { romanji: 'kaisha', answer: 'company' },
  { romanji: 'shachou', answer: 'company president' },
  { romanji: 'kaishain', answer: 'company employee' },
  { romanji: 'hisho', answer: 'secretary' },
  { romanji: 'tenin', answer: 'shop clerk' },
  { romanji: 'isya', answer: 'doctor' },
  { romanji: 'kangofu', answer: 'nurse' },
  { romanji: 'sensei', answer: 'teacher' },
  { romanji: 'gakusei', answer: 'student' },
  { romanji: 'koukousei', answer: 'high school student' },
  { romanji: 'chuugakusei', answer: 'middle school student' },
  { romanji: 'shougakusei', answer: 'elementary student' },
  { romanji: 'okasan', answer: 'mother' },
  { romanji: 'otosan', answer: 'father' },
  { romanji: 'onisan', answer: 'older brother' },
  { romanji: 'oneesan', answer: 'older sister' },
  { romanji: 'imouto', answer: 'younger sister' },
  { romanji: 'otouto', answer: 'younger brother' },
  { romanji: 'sofu', answer: 'grandfather' },
  { romanji: 'sobo', answer: 'grandmother' },
  { romanji: 'kodomo', answer: 'child' },
  { romanji: 'tomodachi', answer: 'friend' },
  { romanji: 'kareshi', answer: 'boyfriend' },
  { romanji: 'kanojo', answer: 'girlfriend' },
  { romanji: 'kazoku', answer: 'family' },
  { romanji: 'kekkon', answer: 'marriage' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'tenki', answer: 'weather' },
  { romanji: 'ame', answer: 'rain' },
  { romanji: 'yuki', answer: 'snow' },
  { romanji: 'kaze', answer: 'wind' },
  { romanji: 'taiyou', answer: 'sun' },
  { romanji: 'tsuki', answer: 'moon' },
  { romanji: 'hoshi', answer: 'star' },
  { romanji: 'jikan', answer: 'time' },
  { romanji: 'hi', answer: 'day' },
  { romanji: 'getsuyoubi', answer: 'Monday' },
  { romanji: 'kayoubi', answer: 'Tuesday' },
  { romanji: 'suiyoubi', answer: 'Wednesday' },
  { romanji: 'mokuyoubi', answer: 'Thursday' },
  { romanji: 'kinyoubi', answer: 'Friday' },
  { romanji: 'doyoubi', answer: 'Saturday' },
  { romanji: 'nichiyoubi', answer: 'Sunday' },
  { romanji: 'gogo', answer: 'afternoon/PM' },
  { romanji: 'gozen', answer: 'morning/AM' },
  { romanji: 'ima', answer: 'now' },
  { romanji: 'kinou', answer: 'yesterday' },
  { romanji: 'ashita', answer: 'tomorrow' },
  { romanji: 'ima kara', answer: 'from now' },
  { romanji: 'saki', answer: 'ahead' },
  { romanji: 'mata', answer: 'again' },
  { romanji: 'yoku', answer: 'often/well' },
  { romanji: 'tokidoki', answer: 'sometimes' },
  { romanji: 'itsumo', answer: 'always' },
  { romanji: 'zenzen', answer: 'not at all' },
  { romanji: 'chotto', answer: 'a little' },
  { romanji: 'totemo', answer: 'very' },
  { romanji: 'hontou ni', answer: 'really' },
  { romanji: 'sugoi', answer: 'amazing' },
  { romanji: 'kawaii', answer: 'cute' },
  { romanji: 'ureshii', answer: 'happy' },
  { romanji: 'kanashii', answer: 'sad' },
  { romanji: 'takai', answer: 'expensive/tall' },
  { romanji: 'yasui', answer: 'cheap' },
  { romanji: 'atarashii', answer: 'new' },
  { romanji: 'furui', answer: 'old' },
  { romanji: 'oishii', answer: 'delicious' },
  { romanji: 'mazui', answer: 'bad tasting' },
  { romanji: 'atsui', answer: 'hot' },
  { romanji: 'samui', answer: 'cold' },
  { romanji: 'omoshiroi', answer: 'interesting' },
  { romanji: 'tsumaranai', answer: 'boring' },
  { romanji: 'hayai', answer: 'fast/early' },
  { romanji: 'osoi', answer: 'slow/late' },
  { romanji: 'ookii', answer: 'big' },
  { romanji: 'chiisai', answer: 'small' },
  { romanji: 'nagai', answer: 'long' },
  { romanji: 'mijikai', answer: 'short' },
  { romanji: 'ii', answer: 'good' },
  { romanji: 'warui', answer: 'bad' }
];


const japaneseWords5 = [
  { romanji: 'arigatou', answer: 'thank you' },
  { romanji: 'sumimasen', answer: 'excuse me / sorry' },
  { romanji: 'onegai', answer: 'please' },
  { romanji: 'daijoubu', answer: 'okay / all right' },
  { romanji: 'wakaranai', answer: 'I don’t understand' },
  { romanji: 'hai', answer: 'yes' },
  { romanji: 'iie', answer: 'no' },
  { romanji: 'moshi moshi', answer: 'hello (on phone)' },
  { romanji: 'ohayou', answer: 'good morning' },
  { romanji: 'konnichiwa', answer: 'good afternoon / hello' },
  { romanji: 'konbanwa', answer: 'good evening' },
  { romanji: 'oyasumi', answer: 'good night' },
  { romanji: 'ittekimasu', answer: 'I’m leaving (home)' },
  { romanji: 'itterasshai', answer: 'have a good day / see you' },
  { romanji: 'tadaima', answer: 'I’m home' },
  { romanji: 'okaeri', answer: 'welcome back' },
  { romanji: 'itadakimasu', answer: 'let’s eat / thank for food' },
  { romanji: 'gochisousama', answer: 'thank you for the meal' },
  { romanji: 'gomen nasai', answer: 'I’m sorry' },
  { romanji: 'otsukaresama', answer: 'good work / thanks for your efforts' },
  { romanji: 'yatta', answer: 'I did it / hooray' },
  { romanji: 'shitsurei shimasu', answer: 'excuse me (formal)' },
  { romanji: 'douzo', answer: 'here you go / please (offer)' },
  { romanji: 'kudasai', answer: 'please give me' },
  { romanji: 'oishii', answer: 'delicious' },
  { romanji: 'mazui', answer: 'bad tasting' },
  { romanji: 'atsui', answer: 'hot (weather/thing)' },
  { romanji: 'samui', answer: 'cold (weather)' },
  { romanji: 'tsumetai', answer: 'cold (thing)' },
  { romanji: 'amai', answer: 'sweet' },
  { romanji: 'karai', answer: 'spicy' },
  { romanji: 'shoppai', answer: 'salty' },
  { romanji: 'nigai', answer: 'bitter' },
  { romanji: 'suki', answer: 'like' },
  { romanji: 'kirai', answer: 'dislike' },
  { romanji: 'ai', answer: 'love' },
  { romanji: 'hobi', answer: 'hobby' },
  { romanji: 'asobi', answer: 'play / fun activity' },
  { romanji: 'benkyou', answer: 'study' },
  { romanji: 'kaimono', answer: 'shopping' },
  { romanji: 'ryouri', answer: 'cooking' },
  { romanji: 'undo', answer: 'exercise' },
  { romanji: 'sanpo', answer: 'walk / stroll' },
  { romanji: 'ryokou', answer: 'travel' },
  { romanji: 'dokusho', answer: 'reading' },
  { romanji: 'ongaku', answer: 'music' },
  { romanji: 'eiga', answer: 'movie' },
  { romanji: 'terebi', answer: 'TV' },
  { romanji: 'geemu', answer: 'game' },
  { romanji: 'supootsu', answer: 'sports' },
  { romanji: 'soccer', answer: 'soccer' },
  { romanji: 'basukettobooru', answer: 'basketball' },
  { romanji: 'tenisu', answer: 'tennis' },
  { romanji: 'yakyuu', answer: 'baseball' },
  { romanji: 'suiei', answer: 'swimming' },
  { romanji: 'jogingu', answer: 'jogging' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'oyogu', answer: 'swim' },
  { romanji: 'aruku', answer: 'walk' },
  { romanji: 'iku', answer: 'go' },
  { romanji: 'kuru', answer: 'come' },
  { romanji: 'kaeru', answer: 'return / go home' },
  { romanji: 'tobu', answer: 'fly / jump' },
  { romanji: 'utau', answer: 'sing' },
  { romanji: 'odorou', answer: 'dance' },
  { romanji: 'kiku', answer: 'listen / ask' },
  { romanji: 'miru', answer: 'see / watch' },
  { romanji: 'taberu', answer: 'eat' },
  { romanji: 'nomu', answer: 'drink' },
  { romanji: 'kaeru', answer: 'change / exchange' },
  { romanji: 'aruku', answer: 'walk' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'neru', answer: 'sleep' },
  { romanji: 'okiru', answer: 'wake up / get up' },
  { romanji: 'abiru', answer: 'take a shower / bathe' },
  { romanji: 'arau', answer: 'wash' },
  { romanji: 'kaku', answer: 'write' },
  { romanji: 'yomu', answer: 'read' },
  { romanji: 'hanasu', answer: 'talk / speak' },
  { romanji: 'iu', answer: 'say' },
  { romanji: 'tatsu', answer: 'stand' },
  { romanji: 'suwaru', answer: 'sit' },
  { romanji: 'shinu', answer: 'die' },
  { romanji: 'ikiru', answer: 'live' },
  { romanji: 'arau', answer: 'wash' },
  { romanji: 'kangaeru', answer: 'think' },
  { romanji: 'wasureru', answer: 'forget' },
  { romanji: 'oboeru', answer: 'remember / memorize' },
  { romanji: 'manabu', answer: 'learn' },
  { romanji: 'shiru', answer: 'know' },
  { romanji: 'wakaru', answer: 'understand' },
  { romanji: 'ugoku', answer: 'move' },
  { romanji: 'tomeru', answer: 'stop' },
  { romanji: 'kaeru', answer: 'return / go home' },
  { romanji: 'okuru', answer: 'send / give' },
  { romanji: 'motsu', answer: 'hold / have' },
  { romanji: 'atsumeru', answer: 'collect / gather' },
  { romanji: 'hanasu', answer: 'release / speak' },
  { romanji: 'kiku', answer: 'listen / hear / ask' },
  { romanji: 'miru', answer: 'see / look' },
  { romanji: 'tabemono o tsukuru', answer: 'cook food' },
  { romanji: 'nomimono o motsu', answer: 'hold a drink' },
  { romanji: 'arubaito o suru', answer: 'work part-time' },
  { romanji: 'benkyou o suru', answer: 'study' },
  { romanji: 'kaimono o suru', answer: 'go shopping' },
  { romanji: 'ryokou o suru', answer: 'travel' },
  { romanji: 'asobu', answer: 'play / have fun' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'oyogu', answer: 'swim' },
  { romanji: 'utau', answer: 'sing' },
  { romanji: 'odorou', answer: 'dance' },
  { romanji: 'hashi o tsukau', answer: 'use chopsticks' },
  { romanji: 'denwa o kakeru', answer: 'make a phone call' },
  { romanji: 'pasokon o tsukau', answer: 'use a computer' },
  { romanji: 'terebi o miru', answer: 'watch TV' },
  { romanji: 'eiga o miru', answer: 'watch a movie' },
  { romanji: 'ongaku o kiku', answer: 'listen to music' },
  { romanji: 'kamera o tsukau', answer: 'use a camera' },
  { romanji: 'shashin o toru', answer: 'take a photo' },
  { romanji: 'ryouri o suru', answer: 'cook / make food' },
  { romanji: 'kurasu ni iku', answer: 'go to class' },
  { romanji: 'shigoto ni iku', answer: 'go to work' },
  { romanji: 'kaisha ni iku', answer: 'go to company' },
  { romanji: 'gakkou ni iku', answer: 'go to school' }
];

const japaneseWords6 = [
  { romanji: 'gakkou kara kaeru', answer: 'return from school' },
  { romanji: 'shigoto kara kaeru', answer: 'return from work' },
  { romanji: 'tomodachi to asobu', answer: 'hang out with friends' },
  { romanji: 'kazoku to asobu', answer: 'spend time with family' },
  { romanji: 'inu to asobu', answer: 'play with a dog' },
  { romanji: 'neko to asobu', answer: 'play with a cat' },
  { romanji: 'hon o yomu', answer: 'read a book' },
  { romanji: 'shinbun o yomu', answer: 'read a newspaper' },
  { romanji: 'zasshi o yomu', answer: 'read a magazine' },
  { romanji: 'tegami o kaku', answer: 'write a letter' },
  { romanji: 'e o kaku', answer: 'draw a picture' },
  { romanji: 'ripooto o kaku', answer: 'write a report' },
  { romanji: 'tanjoobi o iwau', answer: 'celebrate a birthday' },
  { romanji: 'kurisumasu o iwau', answer: 'celebrate Christmas' },
  { romanji: 'shougatsu o iwau', answer: 'celebrate New Year' },
  { romanji: 'ryokou ni iku', answer: 'go on a trip' },
  { romanji: 'hoteru ni tomaru', answer: 'stay at a hotel' },
  { romanji: 'eki ni iku', answer: 'go to the station' },
  { romanji: 'basu ni noru', answer: 'ride a bus' },
  { romanji: 'densha ni noru', answer: 'ride a train' },
  { romanji: 'hikouki ni noru', answer: 'ride an airplane' },
  { romanji: 'kuruma o untensuru', answer: 'drive a car' },
  { romanji: 'jitensha ni noru', answer: 'ride a bicycle' },
  { romanji: 'sanpo suru', answer: 'take a walk' },
  { romanji: 'oyogi ni iku', answer: 'go swimming' },
  { romanji: 'hashiri ni iku', answer: 'go running' },
  { romanji: 'undou suru', answer: 'exercise' },
  { romanji: 'supootsu o suru', answer: 'play sports' },
  { romanji: 'tenisu o suru', answer: 'play tennis' },
  { romanji: 'soccer o suru', answer: 'play soccer' },
  { romanji: 'basukettobooru o suru', answer: 'play basketball' },
  { romanji: 'yakyuu o suru', answer: 'play baseball' },
  { romanji: 'suiei o suru', answer: 'go swimming' },
  { romanji: 'shashin o toru', answer: 'take photos' },
  { romanji: 'kamera o tsukau', answer: 'use a camera' },
  { romanji: 'ongaku o kiku', answer: 'listen to music' },
  { romanji: 'eiga o miru', answer: 'watch a movie' },
  { romanji: 'terebi o miru', answer: 'watch TV' },
  { romanji: 'geemu o suru', answer: 'play a game' },
  { romanji: 'internet o miru', answer: 'browse the internet' },
  { romanji: 'pasokon o tsukau', answer: 'use a computer' },
  { romanji: 'ringo o taberu', answer: 'eat an apple' },
  { romanji: 'mikan o taberu', answer: 'eat a mandarin orange' },
  { romanji: 'banana o taberu', answer: 'eat a banana' },
  { romanji: 'budou o taberu', answer: 'eat grapes' },
  { romanji: 'ichigo o taberu', answer: 'eat a strawberry' },
  { romanji: 'suika o taberu', answer: 'eat a watermelon' },
  { romanji: 'melon o taberu', answer: 'eat a melon' },
  { romanji: 'nashi o taberu', answer: 'eat a pear' },
  { romanji: 'kaki o taberu', answer: 'eat a persimmon' },
  { romanji: 'ume o taberu', answer: 'eat a plum' },
  { romanji: 'tamago o taberu', answer: 'eat an egg' },
  { romanji: 'pan o taberu', answer: 'eat bread' },
  { romanji: 'gohan o taberu', answer: 'eat rice' },
  { romanji: 'yasai o taberu', answer: 'eat vegetables' },
  { romanji: 'sakana o taberu', answer: 'eat fish' },
  { romanji: 'niku o taberu', answer: 'eat meat' },
  { romanji: 'gyuuniku o taberu', answer: 'eat beef' },
  { romanji: 'butaniku o taberu', answer: 'eat pork' },
  { romanji: 'chikin o taberu', answer: 'eat chicken' },
  { romanji: 'mizu o nomu', answer: 'drink water' },
  { romanji: 'ocha o nomu', answer: 'drink tea' },
  { romanji: 'kouhii o nomu', answer: 'drink coffee' },
  { romanji: 'miruku o nomu', answer: 'drink milk' },
  { romanji: 'osu o tsukau', answer: 'use vinegar' },
  { romanji: 'shio o tsukau', answer: 'use salt' },
  { romanji: 'sato o tsukau', answer: 'use sugar' },
  { romanji: 'ninniku o tsukau', answer: 'use garlic' },
  { romanji: 'tamanegi o kiru', answer: 'cut onion' },
  { romanji: 'ninjin o kiru', answer: 'cut carrot' },
  { romanji: 'kyuuri o kiru', answer: 'cut cucumber' },
  { romanji: 'nasu o kiru', answer: 'cut eggplant' },
  { romanji: 'tomato o kiru', answer: 'cut tomato' },
  { romanji: 'retasu o kiru', answer: 'cut lettuce' },
  { romanji: 'horenso o kiru', answer: 'cut spinach' },
  { romanji: 'pīman o kiru', answer: 'cut bell pepper' },
  { romanji: 'kyabetsu o kiru', answer: 'cut cabbage' },
  { romanji: 'hakusai o kiru', answer: 'cut Chinese cabbage' },
  { romanji: 'okashi o tsukuru', answer: 'make sweets' },
  { romanji: 'keeki o tsukuru', answer: 'make cake' },
  { romanji: 'aisu kuriimu o tsukuru', answer: 'make ice cream' },
  { romanji: 'ramen o tsukuru', answer: 'make ramen' },
  { romanji: 'udon o tsukuru', answer: 'make udon noodles' },
  { romanji: 'soba o tsukuru', answer: 'make soba noodles' },
  { romanji: 'sushi o tsukuru', answer: 'make sushi' },
  { romanji: 'sashimi o tsukuru', answer: 'prepare sashimi' },
  { romanji: 'okonomiyaki o tsukuru', answer: 'make okonomiyaki' },
  { romanji: 'takoyaki o tsukuru', answer: 'make takoyaki' },
  { romanji: 'karaage o tsukuru', answer: 'make fried chicken' },
  { romanji: 'tonkatsu o tsukuru', answer: 'make pork cutlet' },
  { romanji: 'yakitori o tsukuru', answer: 'make chicken skewers' },
  { romanji: 'gyoza o tsukuru', answer: 'make dumplings' },
  { romanji: 'misoshiru o tsukuru', answer: 'make miso soup' },
  { romanji: 'salada o tsukuru', answer: 'make salad' },
  { romanji: 'suupu o tsukuru', answer: 'make soup' },
  { romanji: 'ryouri o taberu', answer: 'eat cooked food' },
  { romanji: 'nomimono o nomu', answer: 'drink beverages' },
  { romanji: 'ocha o nomu', answer: 'drink tea' },
  { romanji: 'kouhii o nomu', answer: 'drink coffee' },
  { romanji: 'miruku o nomu', answer: 'drink milk' },
  { romanji: 'mizu o nomu', answer: 'drink water' },
  { romanji: 'osake o nomu', answer: 'drink alcohol' },
  { romanji: 'biiru o nomu', answer: 'drink beer' },
  { romanji: 'wain o nomu', answer: 'drink wine' },
  { romanji: 'shokuji o suru', answer: 'have a meal' },
  { romanji: 'gochisousama o iu', answer: 'say thank you for meal' }
];


const japaneseWords7 = [
  { romanji: 'okiru', answer: 'wake up / get up' },
  { romanji: 'neru', answer: 'sleep' },
  { romanji: 'asobu', answer: 'play / have fun' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'oyogu', answer: 'swim' },
  { romanji: 'utau', answer: 'sing' },
  { romanji: 'odorou', answer: 'dance' },
  { romanji: 'aruku', answer: 'walk' },
  { romanji: 'iku', answer: 'go' },
  { romanji: 'kuru', answer: 'come' },
  { romanji: 'kaeru', answer: 'return / go home' },
  { romanji: 'tatsu', answer: 'stand' },
  { romanji: 'suwaru', answer: 'sit' },
  { romanji: 'shinu', answer: 'die' },
  { romanji: 'ikiru', answer: 'live' },
  { romanji: 'kangaeru', answer: 'think' },
  { romanji: 'wakaru', answer: 'understand' },
  { romanji: 'shiru', answer: 'know' },
  { romanji: 'oboeru', answer: 'remember / memorize' },
  { romanji: 'wasureru', answer: 'forget' },
  { romanji: 'manabu', answer: 'learn' },
  { romanji: 'kiku', answer: 'listen / hear / ask' },
  { romanji: 'miru', answer: 'see / look' },
  { romanji: 'iu', answer: 'say' },
  { romanji: 'kaku', answer: 'write' },
  { romanji: 'arau', answer: 'wash' },
  { romanji: 'abiru', answer: 'take a shower / bathe' },
  { romanji: 'okuru', answer: 'send / give' },
  { romanji: 'motsu', answer: 'hold / have' },
  { romanji: 'atsumeru', answer: 'collect / gather' },
  { romanji: 'hanasu', answer: 'release / speak' },
  { romanji: 'denwa o kakeru', answer: 'make a phone call' },
  { romanji: 'pasokon o tsukau', answer: 'use a computer' },
  { romanji: 'kamera o tsukau', answer: 'use a camera' },
  { romanji: 'shashin o toru', answer: 'take a photo' },
  { romanji: 'ryouri o suru', answer: 'cook / make food' },
  { romanji: 'kaimono o suru', answer: 'go shopping' },
  { romanji: 'benkyou o suru', answer: 'study' },
  { romanji: 'arubaito o suru', answer: 'work part-time' },
  { romanji: 'ryokou o suru', answer: 'travel' },
  { romanji: 'undou o suru', answer: 'exercise' },
  { romanji: 'supootsu o suru', answer: 'play sports' },
  { romanji: 'tenisu o suru', answer: 'play tennis' },
  { romanji: 'soccer o suru', answer: 'play soccer' },
  { romanji: 'basukettobooru o suru', answer: 'play basketball' },
  { romanji: 'yakyuu o suru', answer: 'play baseball' },
  { romanji: 'suiei o suru', answer: 'go swimming' },
  { romanji: 'eiga o miru', answer: 'watch a movie' },
  { romanji: 'terebi o miru', answer: 'watch TV' },
  { romanji: 'ongaku o kiku', answer: 'listen to music' },
  { romanji: 'geemu o suru', answer: 'play a game' },
  { romanji: 'internet o miru', answer: 'browse the internet' },
  { romanji: 'shokuji o suru', answer: 'have a meal' },
  { romanji: 'gochisousama o iu', answer: 'say thank you for meal' },
  { romanji: 'itadakimasu o iu', answer: 'say before meal' },
  { romanji: 'okashi o tsukuru', answer: 'make sweets' },
  { romanji: 'keeki o tsukuru', answer: 'make cake' },
  { romanji: 'aisu kuriimu o tsukuru', answer: 'make ice cream' },
  { romanji: 'ramen o tsukuru', answer: 'make ramen' },
  { romanji: 'udon o tsukuru', answer: 'make udon noodles' },
  { romanji: 'soba o tsukuru', answer: 'make soba noodles' },
  { romanji: 'sushi o tsukuru', answer: 'make sushi' },
  { romanji: 'sashimi o tsukuru', answer: 'prepare sashimi' },
  { romanji: 'okonomiyaki o tsukuru', answer: 'make okonomiyaki' },
  { romanji: 'takoyaki o tsukuru', answer: 'make takoyaki' },
  { romanji: 'karaage o tsukuru', answer: 'make fried chicken' },
  { romanji: 'tonkatsu o tsukuru', answer: 'make pork cutlet' },
  { romanji: 'yakitori o tsukuru', answer: 'make chicken skewers' },
  { romanji: 'gyoza o tsukuru', answer: 'make dumplings' },
  { romanji: 'misoshiru o tsukuru', answer: 'make miso soup' },
  { romanji: 'salada o tsukuru', answer: 'make salad' },
  { romanji: 'suupu o tsukuru', answer: 'make soup' },
  { romanji: 'ringo o taberu', answer: 'eat an apple' },
  { romanji: 'mikan o taberu', answer: 'eat a mandarin orange' },
  { romanji: 'banana o taberu', answer: 'eat a banana' },
  { romanji: 'budou o taberu', answer: 'eat grapes' },
  { romanji: 'ichigo o taberu', answer: 'eat a strawberry' },
  { romanji: 'suika o taberu', answer: 'eat a watermelon' },
  { romanji: 'melon o taberu', answer: 'eat a melon' },
  { romanji: 'nashi o taberu', answer: 'eat a pear' },
  { romanji: 'kaki o taberu', answer: 'eat a persimmon' },
  { romanji: 'ume o taberu', answer: 'eat a plum' },
  { romanji: 'tamago o taberu', answer: 'eat an egg' },
  { romanji: 'pan o taberu', answer: 'eat bread' },
  { romanji: 'gohan o taberu', answer: 'eat rice' },
  { romanji: 'yasai o taberu', answer: 'eat vegetables' },
  { romanji: 'sakana o taberu', answer: 'eat fish' },
  { romanji: 'niku o taberu', answer: 'eat meat' },
  { romanji: 'gyuuniku o taberu', answer: 'eat beef' },
  { romanji: 'butaniku o taberu', answer: 'eat pork' },
  { romanji: 'chikin o taberu', answer: 'eat chicken' },
  { romanji: 'mizu o nomu', answer: 'drink water' },
  { romanji: 'ocha o nomu', answer: 'drink tea' },
  { romanji: 'kouhii o nomu', answer: 'drink coffee' },
  { romanji: 'miruku o nomu', answer: 'drink milk' },
  { romanji: 'osake o nomu', answer: 'drink alcohol' },
  { romanji: 'biiru o nomu', answer: 'drink beer' },
  { romanji: 'wain o nomu', answer: 'drink wine' },
  { romanji: 'osuyu o nomu', answer: 'drink hot water' },
  { romanji: 'misoshiru o nomu', answer: 'drink miso soup' }
];

const japaneseWords8 = [
  { romanji: 'gohan o taberu', answer: 'eat rice / meal' },
  { romanji: 'pan o taberu', answer: 'eat bread' },
  { romanji: 'tamago o taberu', answer: 'eat eggs' },
  { romanji: 'gyuuniku o taberu', answer: 'eat beef' },
  { romanji: 'butaniku o taberu', answer: 'eat pork' },
  { romanji: 'chikin o taberu', answer: 'eat chicken' },
  { romanji: 'sakana o taberu', answer: 'eat fish' },
  { romanji: 'yasai o taberu', answer: 'eat vegetables' },
  { romanji: 'ringo o taberu', answer: 'eat an apple' },
  { romanji: 'mikan o taberu', answer: 'eat a mandarin orange' },
  { romanji: 'banana o taberu', answer: 'eat a banana' },
  { romanji: 'budou o taberu', answer: 'eat grapes' },
  { romanji: 'suika o taberu', answer: 'eat watermelon' },
  { romanji: 'ichigo o taberu', answer: 'eat a strawberry' },
  { romanji: 'nashi o taberu', answer: 'eat a pear' },
  { romanji: 'kaki o taberu', answer: 'eat a persimmon' },
  { romanji: 'ume o taberu', answer: 'eat a plum' },
  { romanji: 'miruku o nomu', answer: 'drink milk' },
  { romanji: 'ocha o nomu', answer: 'drink tea' },
  { romanji: 'kouhii o nomu', answer: 'drink coffee' },
  { romanji: 'mizu o nomu', answer: 'drink water' },
  { romanji: 'osake o nomu', answer: 'drink alcohol / sake' },
  { romanji: 'biiru o nomu', answer: 'drink beer' },
  { romanji: 'wain o nomu', answer: 'drink wine' },
  { romanji: 'shokuji o suru', answer: 'have a meal' },
  { romanji: 'itadakimasu o iu', answer: 'say before meal' },
  { romanji: 'gochisousama o iu', answer: 'say after meal' },
  { romanji: 'ryouri o suru', answer: 'cook food' },
  { romanji: 'sushi o tsukuru', answer: 'make sushi' },
  { romanji: 'sashimi o tsukuru', answer: 'prepare sashimi' },
  { romanji: 'ramen o tsukuru', answer: 'make ramen' },
  { romanji: 'udon o tsukuru', answer: 'make udon noodles' },
  { romanji: 'soba o tsukuru', answer: 'make soba noodles' },
  { romanji: 'okonomiyaki o tsukuru', answer: 'make okonomiyaki' },
  { romanji: 'takoyaki o tsukuru', answer: 'make takoyaki' },
  { romanji: 'karaage o tsukuru', answer: 'make fried chicken' },
  { romanji: 'tonkatsu o tsukuru', answer: 'make pork cutlet' },
  { romanji: 'yakitori o tsukuru', answer: 'make chicken skewers' },
  { romanji: 'gyoza o tsukuru', answer: 'make dumplings' },
  { romanji: 'misoshiru o tsukuru', answer: 'make miso soup' },
  { romanji: 'suupu o tsukuru', answer: 'make soup' },
  { romanji: 'salada o tsukuru', answer: 'make salad' },
  { romanji: 'okashi o tsukuru', answer: 'make sweets' },
  { romanji: 'keeki o tsukuru', answer: 'make cake' },
  { romanji: 'aisu kuriimu o tsukuru', answer: 'make ice cream' },
  { romanji: 'shashin o toru', answer: 'take photos' },
  { romanji: 'kamera o tsukau', answer: 'use a camera' },
  { romanji: 'denwa o kakeru', answer: 'make a phone call' },
  { romanji: 'pasokon o tsukau', answer: 'use a computer' },
  { romanji: 'internet o miru', answer: 'browse the internet' },
  { romanji: 'eiga o miru', answer: 'watch a movie' },
  { romanji: 'terebi o miru', answer: 'watch TV' },
  { romanji: 'ongaku o kiku', answer: 'listen to music' },
  { romanji: 'geemu o suru', answer: 'play a game' },
  { romanji: 'arubaito o suru', answer: 'work part-time' },
  { romanji: 'benkyou o suru', answer: 'study' },
  { romanji: 'ryokou o suru', answer: 'travel' },
  { romanji: 'undou o suru', answer: 'exercise' },
  { romanji: 'supootsu o suru', answer: 'play sports' },
  { romanji: 'tenisu o suru', answer: 'play tennis' },
  { romanji: 'soccer o suru', answer: 'play soccer' },
  { romanji: 'basukettobooru o suru', answer: 'play basketball' },
  { romanji: 'yakyuu o suru', answer: 'play baseball' },
  { romanji: 'suiei o suru', answer: 'go swimming' },
  { romanji: 'asobu', answer: 'play / have fun' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'oyogu', answer: 'swim' },
  { romanji: 'utau', answer: 'sing' },
  { romanji: 'odorou', answer: 'dance' },
  { romanji: 'aruku', answer: 'walk' },
  { romanji: 'iku', answer: 'go' },
  { romanji: 'kuru', answer: 'come' },
  { romanji: 'kaeru', answer: 'return / go home' },
  { romanji: 'tatsu', answer: 'stand' },
  { romanji: 'suwaru', answer: 'sit' },
  { romanji: 'shinu', answer: 'die' },
  { romanji: 'ikiru', answer: 'live' },
  { romanji: 'kangaeru', answer: 'think' },
  { romanji: 'wakaru', answer: 'understand' },
  { romanji: 'shiru', answer: 'know' },
  { romanji: 'oboeru', answer: 'remember / memorize' },
  { romanji: 'wasureru', answer: 'forget' },
  { romanji: 'manabu', answer: 'learn' },
  { romanji: 'kiku', answer: 'listen / hear / ask' },
  { romanji: 'miru', answer: 'see / look' },
  { romanji: 'iu', answer: 'say' },
  { romanji: 'kaku', answer: 'write' },
  { romanji: 'arau', answer: 'wash' },
  { romanji: 'abiru', answer: 'take a shower / bathe' },
  { romanji: 'okuru', answer: 'send / give' },
  { romanji: 'motsu', answer: 'hold / have' },
  { romanji: 'atsumeru', answer: 'collect / gather' },
  { romanji: 'hanasu', answer: 'release / speak' }
];

const japaneseWords9 = [
  { romanji: 'gohan o taberu', answer: 'eat rice / meal' },
  { romanji: 'pan o taberu', answer: 'eat bread' },
  { romanji: 'tamago o taberu', answer: 'eat eggs' },
  { romanji: 'gyuuniku o taberu', answer: 'eat beef' },
  { romanji: 'butaniku o taberu', answer: 'eat pork' },
  { romanji: 'chikin o taberu', answer: 'eat chicken' },
  { romanji: 'sakana o taberu', answer: 'eat fish' },
  { romanji: 'yasai o taberu', answer: 'eat vegetables' },
  { romanji: 'ringo o taberu', answer: 'eat an apple' },
  { romanji: 'mikan o taberu', answer: 'eat a mandarin orange' },
  { romanji: 'banana o taberu', answer: 'eat a banana' },
  { romanji: 'budou o taberu', answer: 'eat grapes' },
  { romanji: 'suika o taberu', answer: 'eat watermelon' },
  { romanji: 'ichigo o taberu', answer: 'eat a strawberry' },
  { romanji: 'nashi o taberu', answer: 'eat a pear' },
  { romanji: 'kaki o taberu', answer: 'eat a persimmon' },
  { romanji: 'ume o taberu', answer: 'eat a plum' },
  { romanji: 'miruku o nomu', answer: 'drink milk' },
  { romanji: 'ocha o nomu', answer: 'drink tea' },
  { romanji: 'kouhii o nomu', answer: 'drink coffee' },
  { romanji: 'mizu o nomu', answer: 'drink water' },
  { romanji: 'osake o nomu', answer: 'drink alcohol / sake' },
  { romanji: 'biiru o nomu', answer: 'drink beer' },
  { romanji: 'wain o nomu', answer: 'drink wine' },
  { romanji: 'shokuji o suru', answer: 'have a meal' },
  { romanji: 'itadakimasu o iu', answer: 'say before meal' },
  { romanji: 'gochisousama o iu', answer: 'say after meal' },
  { romanji: 'ryouri o suru', answer: 'cook food' },
  { romanji: 'sushi o tsukuru', answer: 'make sushi' },
  { romanji: 'sashimi o tsukuru', answer: 'prepare sashimi' },
  { romanji: 'ramen o tsukuru', answer: 'make ramen' },
  { romanji: 'udon o tsukuru', answer: 'make udon noodles' },
  { romanji: 'soba o tsukuru', answer: 'make soba noodles' },
  { romanji: 'okonomiyaki o tsukuru', answer: 'make okonomiyaki' },
  { romanji: 'takoyaki o tsukuru', answer: 'make takoyaki' },
  { romanji: 'karaage o tsukuru', answer: 'make fried chicken' },
  { romanji: 'tonkatsu o tsukuru', answer: 'make pork cutlet' },
  { romanji: 'yakitori o tsukuru', answer: 'make chicken skewers' },
  { romanji: 'gyoza o tsukuru', answer: 'make dumplings' },
  { romanji: 'misoshiru o tsukuru', answer: 'make miso soup' },
  { romanji: 'suupu o tsukuru', answer: 'make soup' },
  { romanji: 'salada o tsukuru', answer: 'make salad' },
  { romanji: 'okashi o tsukuru', answer: 'make sweets' },
  { romanji: 'keeki o tsukuru', answer: 'make cake' },
  { romanji: 'aisu kuriimu o tsukuru', answer: 'make ice cream' },
  { romanji: 'shashin o toru', answer: 'take photos' },
  { romanji: 'kamera o tsukau', answer: 'use a camera' },
  { romanji: 'denwa o kakeru', answer: 'make a phone call' },
  { romanji: 'pasokon o tsukau', answer: 'use a computer' },
  { romanji: 'internet o miru', answer: 'browse the internet' },
  { romanji: 'eiga o miru', answer: 'watch a movie' },
  { romanji: 'terebi o miru', answer: 'watch TV' },
  { romanji: 'ongaku o kiku', answer: 'listen to music' },
  { romanji: 'geemu o suru', answer: 'play a game' },
  { romanji: 'arubaito o suru', answer: 'work part-time' },
  { romanji: 'benkyou o suru', answer: 'study' },
  { romanji: 'ryokou o suru', answer: 'travel' },
  { romanji: 'undou o suru', answer: 'exercise' },
  { romanji: 'supootsu o suru', answer: 'play sports' },
  { romanji: 'tenisu o suru', answer: 'play tennis' },
  { romanji: 'soccer o suru', answer: 'play soccer' },
  { romanji: 'basukettobooru o suru', answer: 'play basketball' },
  { romanji: 'yakyuu o suru', answer: 'play baseball' },
  { romanji: 'suiei o suru', answer: 'go swimming' },
  { romanji: 'asobu', answer: 'play / have fun' },
  { romanji: 'hashiru', answer: 'run' },
  { romanji: 'oyogu', answer: 'swim' },
  { romanji: 'utau', answer: 'sing' },
  { romanji: 'odorou', answer: 'dance' },
  { romanji: 'aruku', answer: 'walk' },
  { romanji: 'iku', answer: 'go' },
  { romanji: 'kuru', answer: 'come' },
  { romanji: 'kaeru', answer: 'return / go home' },
  { romanji: 'tatsu', answer: 'stand' },
  { romanji: 'suwaru', answer: 'sit' },
  { romanji: 'shinu', answer: 'die' },
  { romanji: 'ikiru', answer: 'live' },
  { romanji: 'kangaeru', answer: 'think' },
  { romanji: 'wakaru', answer: 'understand' },
  { romanji: 'shiru', answer: 'know' },
  { romanji: 'oboeru', answer: 'remember / memorize' },
  { romanji: 'wasureru', answer: 'forget' },
  { romanji: 'manabu', answer: 'learn' },
  { romanji: 'kiku', answer: 'listen / hear / ask' },
  { romanji: 'miru', answer: 'see / look' },
  { romanji: 'iu', answer: 'say' },
  { romanji: 'kaku', answer: 'write' },
  { romanji: 'arau', answer: 'wash' },
  { romanji: 'abiru', answer: 'take a shower / bathe' },
  { romanji: 'okuru', answer: 'send / give' },
  { romanji: 'motsu', answer: 'hold / have' },
  { romanji: 'atsumeru', answer: 'collect / gather' },
  { romanji: 'hanasu', answer: 'release / speak' }
];


const japaneseWords = [
          ...japaneseWords1,
          ...japaneseWords2,
          ...japaneseWords3,
          ...japaneseWords4,
          ...japaneseWords5,
          ...japaneseWords6,
          ...japaneseWords7,
          ...japaneseWords8,
          ...japaneseWords9
     ];

export default japaneseWords;