const japaneseWords1 = [
  { romanji:"aoi", japanese:"あおい", answer:"blue" },
  { romanji:"aka", japanese:"あか", answer:"red" },
  { romanji:"akeru", japanese:"あける", answer:"to open (transitive)" },
  { romanji:"aki", japanese:"あき", answer:"autumn" },
  { romanji:"aku", japanese:"あく", answer:"to be empty" },
  { romanji:"ame", japanese:"あめ", answer:"rain" },
  { romanji:"ame", japanese:"あめ", answer:"candy" },
  { romanji:"arasuji", japanese:"あらすじ", answer:"outline, summary" },
  { romanji:"arigatou", japanese:"ありがとう", answer:"thank you" },
  { romanji:"aru", japanese:"ある", answer:"to exist (inanimate)" },
  { romanji:"asa", japanese:"あさ", answer:"morning" },
  { romanji:"asagohan", japanese:"あさごはん", answer:"breakfast" },
  { romanji:"ashita", japanese:"あした", answer:"tomorrow" },
  { romanji:"ashi", japanese:"あし", answer:"leg, foot" },
  { romanji:"baka", japanese:"ばか", answer:"fool, idiot" },
  { romanji:"ban", japanese:"ばん", answer:"evening" },
  { romanji:"bangohan", japanese:"ばんごはん", answer:"dinner" },
  { romanji:"basu", japanese:"バス", answer:"bus" },
  { romanji:"basho", japanese:"ばしょ", answer:"place" },
  { romanji:"benten", japanese:"べんてん", answer:"soap" },
  { romanji:"benkyou", japanese:"べんきょう", answer:"study" },
  { romanji:"bideo", japanese:"ビデオ", answer:"video" },
  { romanji:"bijin", japanese:"びじん", answer:"beautiful woman" },
  { romanji:"bijutsukan", japanese:"びじゅつかん", answer:"art museum" },
  { romanji:"boku", japanese:"ぼく", answer:"I (male)" },
  { romanji:"bun", japanese:"ぶん", answer:"sentence" },
  { romanji:"bunka", japanese:"ぶんか", answer:"culture" },
  { romanji:"bunshou", japanese:"ぶんしょう", answer:"writing, composition" },
  { romanji:"busu", japanese:"ブス", answer:"ugly woman" },
  { romanji:"byouin", japanese:"びょういん", answer:"hospital" },
  { romanji:"byouki", japanese:"びょうき", answer:"illness" },
  { romanji:"cha", japanese:"ちゃ", answer:"tea" },
  { romanji:"chairo", japanese:"ちゃいろ", answer:"brown" },
  { romanji:"chichi", japanese:"ちち", answer:"(my) father" },
  { romanji:"chizu", japanese:"ちず", answer:"map" },
  { romanji:"chotto", japanese:"ちょっと", answer:"a little" },
  { romanji:"chuugoku", japanese:"ちゅうごく", answer:"China" },
  { romanji:"chuugakusei", japanese:"ちゅうがくせい", answer:"middle school student" },
  { romanji:"chuumon", japanese:"ちゅうもん", answer:"order" },
  { romanji:"koe", japanese:"こえ", answer:"voice" },
  { romanji:"koko", japanese:"ここ", answer:"here" },
  { romanji:"kokoro", japanese:"こころ", answer:"heart, mind" },
  { romanji:"kome", japanese:"こめ", answer:"rice (uncooked)" },
  { romanji:"kondo", japanese:"こんど", answer:"next time" },
  { romanji:"kore", japanese:"これ", answer:"this" },
  { romanji:"koto", japanese:"こと", answer:"thing (intangible)" },
  { romanji:"kouen", japanese:"こうえん", answer:"park" },
  { romanji:"koukou", japanese:"こうこう", answer:"high school" },
  { romanji:"kumo", japanese:"くも", answer:"cloud" },
  { romanji:"kumo", japanese:"くも", answer:"spider" },
  { romanji:"kuni", japanese:"くに", answer:"country" },
  { romanji:"kurai", japanese:"くらい", answer:"dark" },
  { romanji:"kuruma", japanese:"くるま", answer:"car" },
  { romanji:"kuroi", japanese:"くろい", answer:"black" },
  { romanji:"kutsu", japanese:"くつ", answer:"shoes" },
  { romanji:"kyou", japanese:"きょう", answer:"today" },
  { romanji:"kyoushitsu", japanese:"きょうしつ", answer:"classroom" },
  { romanji:"kyoumi", japanese:"きょうみ", answer:"interest" }
];


const japaneseWordsPart2 = [
  { romanji:"daigaku", japanese:"だいがく", answer:"university" },
  { romanji:"daigakusei", japanese:"だいがくせい", answer:"university student" },
  { romanji:"daiji", japanese:"だいじ", answer:"important" },
  { romanji:"daijoubu", japanese:"だいじょうぶ", answer:"okay, all right" },
  { romanji:"daikon", japanese:"だいこん", answer:"radish" },
  { romanji:"dare", japanese:"だれ", answer:"who" },
  { romanji:"dareka", japanese:"だれか", answer:"someone" },
  { romanji:"daremo", japanese:"だれも", answer:"no one" },
  { romanji:"daremo", japanese:"だれも", answer:"everyone" },
  { romanji:"de", japanese:"で", answer:"at, in (location marker)" },
  { romanji:"denki", japanese:"でんき", answer:"electricity, light" },
  { romanji:"densha", japanese:"でんしゃ", answer:"train" },
  { romanji:"depāto", japanese:"デパート", answer:"department store" },
  { romanji:"dearu", japanese:"である", answer:"to be" },
  { romanji:"deru", japanese:"でる", answer:"to leave, to exit" },
  { romanji:"doa", japanese:"ドア", answer:"door" },
  { romanji:"doko", japanese:"どこ", answer:"where" },
  { romanji:"dokoka", japanese:"どこか", answer:"somewhere" },
  { romanji:"dore", japanese:"どれ", answer:"which" },
  { romanji:"dou", japanese:"どう", answer:"how" },
  { romanji:"douzo", japanese:"どうぞ", answer:"please" },
  { romanji:"douyatte", japanese:"どうやって", answer:"how (method)" },
  { romanji:"doubutsu", japanese:"どうぶつ", answer:"animal" },
  { romanji:"doyoubi", japanese:"どようび", answer:"Saturday" },
  { romanji:"ebi", japanese:"えび", answer:"shrimp" },
  { romanji:"ee", japanese:"ええ", answer:"yes" },
  { romanji:"ega", japanese:"えいが", answer:"movie" },
  { romanji:"eigakan", japanese:"えいがかん", answer:"movie theater" },
  { romanji:"eigo", japanese:"えいご", answer:"English (language)" },
  { romanji:"eki", japanese:"えき", answer:"station" },
  { romanji:"en", japanese:"えん", answer:"yen" },
  { romanji:"ensoku", japanese:"えんそく", answer:"excursion" },
  { romanji:"fuyu", japanese:"ふゆ", answer:"winter" },
  { romanji:"fuben", japanese:"ふべん", answer:"inconvenient" },
  { romanji:"fuku", japanese:"ふく", answer:"clothes" },
  { romanji:"fukuir", japanese:"ふくいる", answer:"to blow" },
  { romanji:"fune", japanese:"ふね", answer:"boat" },
  { romanji:"furui", japanese:"ふるい", answer:"old (for things)" },
  { romanji:"futari", japanese:"ふたり", answer:"two people" },
  { romanji:"futoi", japanese:"ふとい", answer:"fat, thick" },
  { romanji:"futatsu", japanese:"ふたつ", answer:"two (things)" },
  { romanji:"futon", japanese:"ふとん", answer:"bedding" },
  { romanji:"gakki", japanese:"がっき", answer:"semester" },
  { romanji:"gakkou", japanese:"がっこう", answer:"school" },
  { romanji:"ganbaru", japanese:"がんばる", answer:"to do one’s best" },
  { romanji:"geki", japanese:"げき", answer:"drama, play" },
  { romanji:"genki", japanese:"げんき", answer:"healthy, energetic" },
  { romanji:"getsuyoubi", japanese:"げつようび", answer:"Monday" },
  { romanji:"ginkou", japanese:"ぎんこう", answer:"bank" },
  { romanji:"gyuunyuu", japanese:"ぎゅうにゅう", answer:"milk" },
  { romanji:"haha", japanese:"はは", answer:"(my) mother" },
  { romanji:"hairu", japanese:"はいる", answer:"to enter" },
  { romanji:"hajimaru", japanese:"はじまる", answer:"to begin (intransitive)" },
  { romanji:"hajimeru", japanese:"はじめる", answer:"to begin (transitive)" },
  { romanji:"haka", japanese:"はか", answer:"grave" },
  { romanji:"hako", japanese:"はこ", answer:"box" },
  { romanji:"hana", japanese:"はな", answer:"nose" },
  { romanji:"hana", japanese:"はな", answer:"flower" },
  { romanji:"hanasu", japanese:"はなす", answer:"to speak" },
  { romanji:"hane", japanese:"はね", answer:"feather, wing" },
  { romanji:"hantai", japanese:"はんたい", answer:"opposite, objection" },
  { romanji:"hanbaagu", japanese:"ハンバーグ", answer:"hamburger (steak)" },
  { romanji:"happa", japanese:"はっぱ", answer:"leaf" },
  { romanji:"haru", japanese:"はる", answer:"spring" },
  { romanji:"hashi", japanese:"はし", answer:"chopsticks" },
  { romanji:"hashi", japanese:"はし", answer:"bridge" },
  { romanji:"hataraku", japanese:"はたらく", answer:"to work" },
  { romanji:"hayai", japanese:"はやい", answer:"fast, early" },
  { romanji:"heya", japanese:"へや", answer:"room" },
  { romanji:"hiru", japanese:"ひる", answer:"noon" },
  { romanji:"hirugohan", japanese:"ひるごはん", answer:"lunch" },
  { romanji:"hito", japanese:"ひと", answer:"person" },
  { romanji:"hitotsu", japanese:"ひとつ", answer:"one (thing)" },
  { romanji:"hon", japanese:"ほん", answer:"book" },
  { romanji:"honya", japanese:"ほんや", answer:"bookstore" }
];

const japaneseWordsPart3 = [
  { romanji:"ie", japanese:"いえ", answer:"house" },
  { romanji:"igaku", japanese:"いがく", answer:"medical science" },
  { romanji:"ii", japanese:"いい", answer:"good" },
  { romanji:"iie", japanese:"いいえ", answer:"no" },
  { romanji:"iku", japanese:"いく", answer:"to go" },
  { romanji:"ikura", japanese:"いくら", answer:"how much" },
  { romanji:"ima", japanese:"いま", answer:"now" },
  { romanji:"ima", japanese:"いま", answer:"living room" },
  { romanji:"imouto", japanese:"いもうと", answer:"younger sister" },
  { romanji:"inaka", japanese:"いなか", answer:"countryside" },
  { romanji:"inu", japanese:"いぬ", answer:"dog" },
  { romanji:"ippai", japanese:"いっぱい", answer:"a lot, full" },
  { romanji:"iriguchi", japanese:"いりぐち", answer:"entrance" },
  { romanji:"iru", japanese:"いる", answer:"to exist (animate)" },
  { romanji:"iro", japanese:"いろ", answer:"color" },
  { romanji:"iroiro", japanese:"いろいろ", answer:"various" },
  { romanji:"jikan", japanese:"じかん", answer:"time, hour" },
  { romanji:"jikanwari", japanese:"じかんわり", answer:"schedule" },
  { romanji:"jisho", japanese:"じしょ", answer:"dictionary" },
  { romanji:"joubu", japanese:"じょうぶ", answer:"strong, durable" },
  { romanji:"jousu", japanese:"じょうず", answer:"skilled" },
  { romanji:"junkan", japanese:"じゅんかん", answer:"circulation" },
  { romanji:"jyu", japanese:"じゅう", answer:"ten" },
  { romanji:"jyugyou", japanese:"じゅぎょう", answer:"class, lesson" },
  { romanji:"jyoubu", japanese:"じょうぶ", answer:"strong, healthy" },
  { romanji:"jyozu", japanese:"じょうず", answer:"good at" },
  { romanji:"jyunbi", japanese:"じゅんび", answer:"preparation" },
  { romanji:"jyo", japanese:"じょ", answer:"female prefix" },
  { romanji:"ka", japanese:"か", answer:"mosquito" },
  { romanji:"kaado", japanese:"カード", answer:"card" },
  { romanji:"kaerimasu", japanese:"かえります", answer:"to return" },
  { romanji:"kaeru", japanese:"かえる", answer:"frog" },
  { romanji:"kagi", japanese:"かぎ", answer:"key" },
  { romanji:"kagaku", japanese:"かがく", answer:"science" },
  { romanji:"kakaru", japanese:"かかる", answer:"to take (time/money)" },
  { romanji:"kakikata", japanese:"かきかた", answer:"how to write" },
  { romanji:"kaku", japanese:"かく", answer:"to write" },
  { romanji:"kakko", japanese:"かっこ", answer:"parentheses" },
  { romanji:"kakkoii", japanese:"かっこいい", answer:"cool, attractive" },
  { romanji:"kami", japanese:"かみ", answer:"hair" },
  { romanji:"kami", japanese:"かみ", answer:"paper" },
  { romanji:"kan", japanese:"かん", answer:"can (metal)" },
  { romanji:"kanari", japanese:"かなり", answer:"considerably" },
  { romanji:"kanji", japanese:"かんじ", answer:"kanji" },
  { romanji:"karai", japanese:"からい", answer:"spicy" },
  { romanji:"karasu", japanese:"からす", answer:"crow" },
  { romanji:"kare", japanese:"かれ", answer:"he, boyfriend" },
  { romanji:"kasa", japanese:"かさ", answer:"umbrella" },
  { romanji:"kata", japanese:"かた", answer:"person (polite)" },
  { romanji:"katakana", japanese:"カタカナ", answer:"katakana" },
  { romanji:"kawarimono", japanese:"かわりもの", answer:"odd person" },
  { romanji:"kawaii", japanese:"かわいい", answer:"cute" },
  { romanji:"keeki", japanese:"ケーキ", answer:"cake" },
  { romanji:"kedo", japanese:"けど", answer:"but" },
  { romanji:"keisatsu", japanese:"けいさつ", answer:"police" },
  { romanji:"kekkon", japanese:"けっこん", answer:"marriage" },
  { romanji:"kesa", japanese:"けさ", answer:"this morning" },
  { romanji:"keshigomu", japanese:"けしごむ", answer:"eraser" },
  { romanji:"ki", japanese:"き", answer:"tree" },
  { romanji:"kibishii", japanese:"きびしい", answer:"strict" },
  { romanji:"kikoeru", japanese:"きこえる", answer:"to be heard" },
  { romanji:"kiku", japanese:"きく", answer:"to listen, to ask" },
  { romanji:"kimono", japanese:"きもの", answer:"kimono" },
  { romanji:"kinou", japanese:"きのう", answer:"yesterday" },
  { romanji:"kirai", japanese:"きらい", answer:"dislike" },
  { romanji:"kirei", japanese:"きれい", answer:"pretty, clean" },
  { romanji:"kisetsu", japanese:"きせつ", answer:"season" },
  { romanji:"kissaten", japanese:"きっさてん", answer:"coffee shop" },
  { romanji:"kitte", japanese:"きって", answer:"postage stamp" },
  { romanji:"kiyoi", japanese:"きよい", answer:"pure" },
  { romanji:"ko", japanese:"こ", answer:"child suffix" },
  { romanji:"koe", japanese:"こえ", answer:"voice" },
  { romanji:"koko", japanese:"ここ", answer:"here" },
  { romanji:"kokoro", japanese:"こころ", answer:"heart, mind" },
  { romanji:"kome", japanese:"こめ", answer:"rice (uncooked)" },
  { romanji:"komaru", japanese:"こまる", answer:"to be troubled" },
  { romanji:"konban", japanese:"こんばん", answer:"tonight" },
  { romanji:"konnichiwa", japanese:"こんにちは", answer:"hello" },
  { romanji:"konshuu", japanese:"こんしゅう", answer:"this week" },
  { romanji:"kotoshi", japanese:"ことし", answer:"this year" },
  { romanji:"kouen", japanese:"こうえん", answer:"park" },
  { romanji:"kumo", japanese:"くも", answer:"cloud" },
  { romanji:"kurasu", japanese:"クラス", answer:"class" },
  { romanji:"kuruma", japanese:"くるま", answer:"car" },
  { romanji:"kusa", japanese:"くさ", answer:"grass" },
  { romanji:"machi", japanese:"まち", answer:"town" },
  { romanji:"madoguchi", japanese:"まどぐち", answer:"service window" },
  { romanji:"mae", japanese:"まえ", answer:"before, in front" },
  { romanji:"mahou", japanese:"まほう", answer:"magic" },
  { romanji:"mai", japanese:"まい", answer:"counter for flat objects" },
  { romanji:"mainichi", japanese:"まいにち", answer:"every day" },
  { romanji:"maishuu", japanese:"まいしゅう", answer:"every week" },
  { romanji:"maitoshi", japanese:"まいとし", answer:"every year" },
  { romanji:"makasu", japanese:"まかす", answer:"to defeat" },
  { romanji:"mama", japanese:"まま", answer:"so-so" },
  { romanji:"mame", japanese:"まめ", answer:"bean" },
  { romanji:"manga", japanese:"まんが", answer:"comic, manga" },
  { romanji:"matsu", japanese:"まつ", answer:"to wait" },
  { romanji:"mazui", japanese:"まずい", answer:"bad-tasting" },
  { romanji:"meari", japanese:"メアリ", answer:"Mary" },
  { romanji:"megane", japanese:"めがね", answer:"glasses" },
  { romanji:"meishi", japanese:"めいし", answer:"business card" }
];


const japaneseWordsPart4 = [
  { romanji:"naka", japanese:"なか", answer:"inside" },
  { romanji:"nakusu", japanese:"なくす", answer:"to lose something" },
  { romanji:"namae", japanese:"なまえ", answer:"name" },
  { romanji:"nami", japanese:"なみ", answer:"wave" },
  { romanji:"nani", japanese:"なに", answer:"what" },
  { romanji:"narau", japanese:"ならう", answer:"to learn" },
  { romanji:"naru", japanese:"なる", answer:"to become" },
  { romanji:"nattsu", japanese:"なっつ", answer:"nuts" },
  { romanji:"natsu", japanese:"なつ", answer:"summer" },
  { romanji:"naze", japanese:"なぜ", answer:"why" },
  { romanji:"ne", japanese:"ね", answer:"isn't it? (particle)" },
  { romanji:"neko", japanese:"ねこ", answer:"cat" },
  { romanji:"nemu", japanese:"ねむ", answer:"sleepy" },
  { romanji:"neru", japanese:"ねる", answer:"to sleep" },
  { romanji:"netsu", japanese:"ねつ", answer:"fever" },
  { romanji:"ni", japanese:"に", answer:"to (direction particle)" },
  { romanji:"niku", japanese:"にく", answer:"meat" },
  { romanji:"nihon", japanese:"にほん", answer:"Japan" },
  { romanji:"nihongo", japanese:"にほんご", answer:"Japanese language" },
  { romanji:"niji", japanese:"にじ", answer:"rainbow" },
  { romanji:"nikuya", japanese:"にくや", answer:"butcher shop" },
  { romanji:"nimotsu", japanese:"にもつ", answer:"luggage" },
  { romanji:"ninjin", japanese:"にんじん", answer:"carrot" },
  { romanji:"nodo", japanese:"のど", answer:"throat" },
  { romanji:"noriba", japanese:"のりば", answer:"place to board (bus/taxi)" },
  { romanji:"norimono", japanese:"のりもの", answer:"vehicle" },
  { romanji:"noru", japanese:"のる", answer:"to ride" },
  { romanji:"obaasan", japanese:"おばあさん", answer:"grandmother" },
  { romanji:"obasan", japanese:"おばさん", answer:"aunt" },
  { romanji:"oba", japanese:"おば", answer:"(my) aunt" },
  { romanji:"ocha", japanese:"おちゃ", answer:"tea" },
  { romanji:"odori", japanese:"おどり", answer:"dance" },
  { romanji:"odoru", japanese:"おどる", answer:"to dance" },
  { romanji:"oe", japanese:"おえ", answer:"vomit (slang)" },
  { romanji:"oishii", japanese:"おいしい", answer:"delicious" },
  { romanji:"ojiisan", japanese:"おじいさん", answer:"grandfather" },
  { romanji:"ojisan", japanese:"おじさん", answer:"uncle" },
  { romanji:"okaasan", japanese:"おかあさん", answer:"mother (polite)" },
  { romanji:"okane", japanese:"おかね", answer:"money" },
  { romanji:"okashi", japanese:"おかし", answer:"snacks" },
  { romanji:"okeru", japanese:"おける", answer:"to place (literary)" },
  { romanji:"okiru", japanese:"おきる", answer:"to wake up" },
  { romanji:"okyaku", japanese:"おきゃく", answer:"guest" },
  { romanji:"omae", japanese:"おまえ", answer:"you (casual)" },
  { romanji:"omatsuri", japanese:"おまつり", answer:"festival" },
  { romanji:"omo", japanese:"おも", answer:"main" },
  { romanji:"omoi", japanese:"おもい", answer:"heavy" },
  { romanji:"omoshiroi", japanese:"おもしろい", answer:"interesting, funny" },
  { romanji:"onaka", japanese:"おなか", answer:"stomach" },
  { romanji:"onegai", japanese:"おねがい", answer:"please (request)" },
  { romanji:"oni", japanese:"おに", answer:"ogre, demon" },
  { romanji:"onna", japanese:"おんな", answer:"woman" },
  { romanji:"otoko", japanese:"おとこ", answer:"man" },
  { romanji:"oto", japanese:"おと", answer:"sound" },
  { romanji:"ototoi", japanese:"おととい", answer:"day before yesterday" },
  { romanji:"otooto", japanese:"おとうと", answer:"younger brother" },
  { romanji:"otousan", japanese:"おとうさん", answer:"father (polite)" },
  { romanji:"oyogi", japanese:"およぎ", answer:"swimming" },
  { romanji:"oyogu", japanese:"およぐ", answer:"to swim" },
  { romanji:"oyasumi", japanese:"おやすみ", answer:"good night" },
  { romanji:"pan", japanese:"パン", answer:"bread" },
  { romanji:"pen", japanese:"ペン", answer:"pen" },
  { romanji:"piano", japanese:"ピアノ", answer:"piano" },
  { romanji:"puuru", japanese:"プール", answer:"pool" },
  { romanji:"raishuu", japanese:"らいしゅう", answer:"next week" },
  { romanji:"rainen", japanese:"らいねん", answer:"next year" },
  { romanji:"ramen", japanese:"ラーメン", answer:"ramen" },
  { romanji:"rekishi", japanese:"れきし", answer:"history" },
  { romanji:"renraku", japanese:"れんらく", answer:"contact" },
  { romanji:"renshuu", japanese:"れんしゅう", answer:"practice" },
  { romanji:"ringo", japanese:"りんご", answer:"apple" },
  { romanji:"rokku", japanese:"ロック", answer:"rock (music)" },
  { romanji:"rusu", japanese:"るす", answer:"absence" },
  { romanji:"sakana", japanese:"さかな", answer:"fish" },
  { romanji:"sakura", japanese:"さくら", answer:"cherry blossom" },
  { romanji:"samui", japanese:"さむい", answer:"cold (weather)" },
  { romanji:"san", japanese:"さん", answer:"three" },
  { romanji:"sara", japanese:"さら", answer:"plate" },
  { romanji:"saru", japanese:"さる", answer:"monkey" },
  { romanji:"sato", japanese:"さと", answer:"village" },
  { romanji:"sayonara", japanese:"さよなら", answer:"goodbye" },
  { romanji:"seito", japanese:"せいと", answer:"student" },
  { romanji:"sekai", japanese:"せかい", answer:"world" },
  { romanji:"sen", japanese:"せん", answer:"thousand" },
  { romanji:"sensei", japanese:"せんせい", answer:"teacher" },
  { romanji:"shinbun", japanese:"しんぶん", answer:"newspaper" },
  { romanji:"shio", japanese:"しお", answer:"salt" },
  { romanji:"shiroi", japanese:"しろい", answer:"white" },
  { romanji:"shita", japanese:"した", answer:"down, below" },
  { romanji:"shizuka", japanese:"しずか", answer:"quiet" },
  { romanji:"shokuji", japanese:"しょくじ", answer:"meal" },
  { romanji:"soba", japanese:"そば", answer:"near" },
  { romanji:"sora", japanese:"そら", answer:"sky" },
  { romanji:"soto", japanese:"そと", answer:"outside" },
  { romanji:"ta", japanese:"た", answer:"rice field" },
  { romanji:"tabemono", japanese:"たべもの", answer:"food" },
  { romanji:"taberu", japanese:"たべる", answer:"to eat" },
  { romanji:"tada", japanese:"ただ", answer:"free (no cost)" },
  { romanji:"taihen", japanese:"たいへん", answer:"serious, terrible" },
  { romanji:"taiko", japanese:"たいこ", answer:"drum" },
  { romanji:"takai", japanese:"たかい", answer:"tall, expensive" },
  { romanji:"tako", japanese:"たこ", answer:"octopus" },
  { romanji:"tamago", japanese:"たまご", answer:"egg" },
  { romanji:"tanoshii", japanese:"たのしい", answer:"fun" },
  { romanji:"tanoshimu", japanese:"たのしむ", answer:"to enjoy" },
  { romanji:"tanomu", japanese:"たのむ", answer:"to ask, to request" },
  { romanji:"tatami", japanese:"たたみ", answer:"tatami mat" },
  { romanji:"tatoeba", japanese:"たとえば", answer:"for example" },
  { romanji:"tegami", japanese:"てがみ", answer:"letter" },
  { romanji:"te", japanese:"て", answer:"hand" },
  { romanji:"tenki", japanese:"てんき", answer:"weather" },
  { romanji:"terebi", japanese:"テレビ", answer:"television" },
  { romanji:"to", japanese:"と", answer:"and (particle)" },
  { romanji:"tokei", japanese:"とけい", answer:"clock, watch" },
  { romanji:"tokoro", japanese:"ところ", answer:"place" },
  { romanji:"tomodachi", japanese:"ともだち", answer:"friend" },
  { romanji:"tonari", japanese:"となり", answer:"next to" },
  { romanji:"toru", japanese:"とる", answer:"to take" },
  { romanji:"tori", japanese:"とり", answer:"bird" },
  { romanji:"tsuchi", japanese:"つち", answer:"soil" },
  { romanji:"tsuki", japanese:"つき", answer:"moon" },
  { romanji:"tsukuru", japanese:"つくる", answer:"to make" },
  { romanji:"tsumetai", japanese:"つめたい", answer:"cold (to touch)" },
  { romanji:"tsuyoi", japanese:"つよい", answer:"strong" },
  { romanji:"uchi", japanese:"うち", answer:"house, home" },
  { romanji:"udon", japanese:"うどん", answer:"udon" },
  { romanji:"ue", japanese:"うえ", answer:"above" },
  { romanji:"uma", japanese:"うま", answer:"horse" },
  { romanji:"umi", japanese:"うみ", answer:"sea" },
  { romanji:"umu", japanese:"うむ", answer:"to give birth" },
  { romanji:"umu", japanese:"うむ", answer:"to produce" },
  { romanji:"ura", japanese:"うら", answer:"backside" },
  { romanji:"ushi", japanese:"うし", answer:"cow" },
  { romanji:"uso", japanese:"うそ", answer:"lie" },
  { romanji:"utsukushii", japanese:"うつくしい", answer:"beautiful" },
  { romanji:"uuru", japanese:"うーる", answer:"wool" },
  { romanji:"wakai", japanese:"わかい", answer:"young" },
  { romanji:"wakaru", japanese:"わかる", answer:"to understand" },
  { romanji:"warau", japanese:"わらう", answer:"to laugh" },
  { romanji:"washi", japanese:"わし", answer:"eagle" },
  { romanji:"watashi", japanese:"わたし", answer:"I / me" },
  { romanji:"watashi-tachi", japanese:"わたしたち", answer:"we" },
  { romanji:"yama", japanese:"やま", answer:"mountain" },
  { romanji:"yameru", japanese:"やめる", answer:"to stop" },
  { romanji:"yasai", japanese:"やさい", answer:"vegetable" },
  { romanji:"yasui", japanese:"やすい", answer:"cheap" },
  { romanji:"yasumi", japanese:"やすみ", answer:"rest, holiday" },
  { romanji:"yuki", japanese:"ゆき", answer:"snow" },
  { romanji:"yume", japanese:"ゆめ", answer:"dream" },
  { romanji:"yureru", japanese:"ゆれる", answer:"to shake" },
  { romanji:"yuu", japanese:"ゆう", answer:"evening" },
  { romanji:"yubi", japanese:"ゆび", answer:"finger" },
  { romanji:"yuka", japanese:"ゆか", answer:"floor" },
  { romanji:"yumei", japanese:"ゆうめい", answer:"famous" },
  { romanji:"zakka", japanese:"ざっか", answer:"general goods" },
  { romanji:"zasshi", japanese:"ざっし", answer:"magazine" },
  { romanji:"zenbu", japanese:"ぜんぶ", answer:"all" },
  { romanji:"zou", japanese:"ぞう", answer:"elephant" }
];

const japaneseWordsN4_Part5 = [
  { romanji:"abunai", japanese:"あぶない", answer:"dangerous" },
  { romanji:"agaru", japanese:"あがる", answer:"to rise, go up" },
  { romanji:"agete", japanese:"あげて", answer:"to give" },
  { romanji:"aji", japanese:"あじ", answer:"flavor" },
  { romanji:"aka-chan", japanese:"あかちゃん", answer:"baby" },
  { romanji:"akeru", japanese:"あける", answer:"to open" },
  { romanji:"akiramete", japanese:"あきらめて", answer:"to give up" },
  { romanji:"akiraka", japanese:"あきらか", answer:"clear, obvious" },
  { romanji:"aku", japanese:"あく", answer:"to open (intransitive)" },
  { romanji:"amari", japanese:"あまり", answer:"not very, not much" },
  { romanji:"amai", japanese:"あまい", answer:"sweet" },
  { romanji:"amari-ni", japanese:"あまりに", answer:"too (much), excessively" },
  { romanji:"anzen", japanese:"あんぜん", answer:"safe" },
  { romanji:"anshin", japanese:"あんしん", answer:"relief" },
  { romanji:"annai", japanese:"あんない", answer:"guidance, information" },

  { romanji:"araigoto", japanese:"あらいごと", answer:"laundry" },
  { romanji:"arawareru", japanese:"あらわれる", answer:"to appear" },
  { romanji:"arau", japanese:"あらう", answer:"to wash" },
  { romanji:"ariki", japanese:"ありき", answer:"existing, usual" },
  { romanji:"arigatai", japanese:"ありがたい", answer:"thankful" },

  { romanji:"asobi", japanese:"あそび", answer:"play" },
  { romanji:"ataeru", japanese:"あたえる", answer:"to give, to provide" },
  { romanji:"atai", japanese:"あたい", answer:"value, price" },
  { romanji:"atarashii", japanese:"あたらしい", answer:"new" },
  { romanji:"atari", japanese:"あたり", answer:"hit, success" },
  { romanji:"atarimae", japanese:"あたりまえ", answer:"natural, obvious" },
  { romanji:"ataru", japanese:"あたる", answer:"to hit, to win" },

  { romanji:"atorakku", japanese:"アトラク", answer:"attraction" },
  { romanji:"atsui", japanese:"あつい", answer:"hot (weather)" },
  { romanji:"atsumaru", japanese:"あつまる", answer:"to gather" },
  { romanji:"atsumeru", japanese:"あつめる", answer:"to collect" },

  { romanji:"ayamaru", japanese:"あやまる", answer:"to apologize" },
  { romanji:"ayamachi", japanese:"あやまち", answer:"mistake" },

  { romanji:"abaabā", japanese:"アバター", answer:"avatar" },
  { romanji:"abura", japanese:"あぶら", answer:"oil" },
  { romanji:"aburui", japanese:"あぶるい", answer:"to broil, grill lightly" },

  { romanji:"ajiwaru", japanese:"あじわる", answer:"to savor" },
  { romanji:"azukaru", japanese:"あずかる", answer:"to look after, to keep" },
  { romanji:"azukeru", japanese:"あずける", answer:"to deposit, entrust" },

  { romanji:"anzen-na", japanese:"あんぜんな", answer:"safe (na-adjective)" },
  { romanji:"arashi", japanese:"あらし", answer:"storm" },
  { romanji:"are", japanese:"あれ", answer:"that (over there)" },

  { romanji:"asobu", japanese:"あそぶ", answer:"to play, hang out" },
  { romanji:"atarashiku", japanese:"あたらしく", answer:"newly" },
  { romanji:"atta", japanese:"あった", answer:"was, existed" }
];

const japaneseWordsN4_Part6 = [
  { romanji:"baai", japanese:"ばあい", answer:"case, situation" },
  { romanji:"baiku", japanese:"バイク", answer:"motorcycle" },
  { romanji:"bandai", japanese:"ばんだい", answer:"counter, checkout" },
  { romanji:"bankoku", japanese:"ばんこく", answer:"all countries" },
  { romanji:"bara", japanese:"ばら", answer:"rose" },
  { romanji:"bareru", japanese:"ばれる", answer:"to be exposed, found out" },

  { romanji:"benri", japanese:"べんり", answer:"convenient" },
  { romanji:"betsu", japanese:"べつ", answer:"separate, another" },
  { romanji:"betsuni", japanese:"べつに", answer:"not particularly" },

  { romanji:"bijutsukan", japanese:"びじゅつかん", answer:"art museum" },
  { romanji:"bin", japanese:"びん", answer:"bottle" },
  { romanji:"binkan", japanese:"びんかん", answer:"sensitive" },

  { romanji:"boku", japanese:"ぼく", answer:"I (male)" },
  { romanji:"bokutachi", japanese:"ぼくたち", answer:"we (male)" },

  { romanji:"boshuu", japanese:"ぼしゅう", answer:"recruitment" },
  { romanji:"bokashi", japanese:"ぼかし", answer:"blur, gradation" },

  { romanji:"bu", japanese:"ぶ", answer:"club, department" },
  { romanji:"buchou", japanese:"ぶちょう", answer:"department chief" },
  { romanji:"budou", japanese:"ぶどう", answer:"grape" },
  { romanji:"bukiyou", japanese:"ぶきよう", answer:"clumsy" },

  { romanji:"bun", japanese:"ぶん", answer:"portion" },
  { romanji:"bunbougu", japanese:"ぶんぼうぐ", answer:"stationery" },
  { romanji:"bungaku", japanese:"ぶんがく", answer:"literature" },
  { romanji:"bunpou", japanese:"ぶんぽう", answer:"grammar" },

  { romanji:"busu", japanese:"ぶす", answer:"ugly (slang)" },

  { romanji:"byouin", japanese:"びょういん", answer:"hospital" },
  { romanji:"byouki", japanese:"びょうき", answer:"illness" },
  { romanji:"byouki-naru", japanese:"びょうきなる", answer:"to fall sick" },

  { romanji:"bunkai", japanese:"ぶんかい", answer:"analysis, disassembly" },
  { romanji:"bunrui", japanese:"ぶんるい", answer:"classification" },

  { romanji:"baito", japanese:"バイト", answer:"part-time job" },
  { romanji:"baabekyuu", japanese:"バーベキュー", answer:"barbecue" },

  { romanji:"biiru", japanese:"ビール", answer:"beer" },
  { romanji:"biru", japanese:"ビル", answer:"building" },
  { romanji:"biriben", japanese:"びりべん", answer:"studying like crazy (slang)" }
];

const japaneseWordsN4_Part7 = [
  { romanji:"chanto", japanese:"ちゃんと", answer:"properly, correctly" },
  { romanji:"chanto-suru", japanese:"ちゃんとする", answer:"to do properly" },

  { romanji:"chigau", japanese:"ちがう", answer:"to differ, to be wrong" },
  { romanji:"chikaku", japanese:"ちかく", answer:"nearby" },
  { romanji:"chika", japanese:"ちか", answer:"basement" },
  { romanji:"chikatta", japanese:"ちかった", answer:"was close" },

  { romanji:"chizu", japanese:"ちず", answer:"map" },
  { romanji:"chikara", japanese:"ちから", answer:"strength, power" },
  { romanji:"chime", japanese:"チャイム", answer:"chime, bell" },

  { romanji:"chindogu", japanese:"ちんどうぐ", answer:"weird/inventive tool" },

  { romanji:"choushi", japanese:"ちょうし", answer:"condition, tone" },
  { romanji:"chotto", japanese:"ちょっと", answer:"a little" },
  { romanji:"chuumon", japanese:"ちゅうもん", answer:"order (at restaurant)" },
  { romanji:"chuugoku", japanese:"ちゅうごく", answer:"China" },
  { romanji:"chuugakusei", japanese:"ちゅうがくせい", answer:"middle school student" },
  { romanji:"chuui", japanese:"ちゅうい", answer:"attention, caution" },
  { romanji:"chuusha", japanese:"ちゅうしゃ", answer:"parking; injection" },
  { romanji:"chuushajou", japanese:"ちゅうしゃじょう", answer:"parking lot" },

  { romanji:"daaku", japanese:"ダーク", answer:"dark" },
  { romanji:"daijina", japanese:"だいじな", answer:"important" },
  { romanji:"daiji", japanese:"だいじ", answer:"important" },
  { romanji:"daijin", japanese:"だいじん", answer:"minister" },

  { romanji:"daikirai", japanese:"だいきらい", answer:"hate (strong)" },
  { romanji:"daisuki", japanese:"だいすき", answer:"love, really like" },

  { romanji:"danshi", japanese:"だんし", answer:"boy, male" },
  { romanji:"danshi-sei", japanese:"だんしせい", answer:"male student" },
  { romanji:"dansou", japanese:"だんそう", answer:"generation gap" },

  { romanji:"dekakeru", japanese:"でかける", answer:"to go out" },
  { romanji:"dekiru", japanese:"できる", answer:"can do; be able to" },
  { romanji:"demasu", japanese:"でます", answer:"to go out; to leave" },

  { romanji:"denshi", japanese:"でんし", answer:"electronic" },
  { romanji:"denshi-jisho", japanese:"でんしじしょ", answer:"electronic dictionary" },

  { romanji:"doro", japanese:"どろ", answer:"mud" },
  { romanji:"dorobou", japanese:"どろぼう", answer:"thief" },

  { romanji:"dougu", japanese:"どうぐ", answer:"tool" },
  { romanji:"douka", japanese:"どうか", answer:"please" },
  { romanji:"douji", japanese:"どうじ", answer:"same time" },
  { romanji:"douka-shiteiru", japanese:"どうかしている", answer:"crazy, weird" }
];


const japaneseWordsN4_Part8 = [
  { romanji:"chanto", japanese:"ちゃんと", answer:"properly, correctly" },
  { romanji:"chanto-suru", japanese:"ちゃんとする", answer:"to do properly" },

  { romanji:"chigau", japanese:"ちがう", answer:"to differ, to be wrong" },
  { romanji:"chikaku", japanese:"ちかく", answer:"nearby" },
  { romanji:"chika", japanese:"ちか", answer:"basement" },
  { romanji:"chikatta", japanese:"ちかった", answer:"was close" },

  { romanji:"chizu", japanese:"ちず", answer:"map" },
  { romanji:"chikara", japanese:"ちから", answer:"strength, power" },
  { romanji:"chime", japanese:"チャイム", answer:"chime, bell" },

  { romanji:"chindogu", japanese:"ちんどうぐ", answer:"weird/inventive tool" },

  { romanji:"choushi", japanese:"ちょうし", answer:"condition, tone" },
  { romanji:"chotto", japanese:"ちょっと", answer:"a little" },
  { romanji:"chuumon", japanese:"ちゅうもん", answer:"order (at restaurant)" },
  { romanji:"chuugoku", japanese:"ちゅうごく", answer:"China" },
  { romanji:"chuugakusei", japanese:"ちゅうがくせい", answer:"middle school student" },
  { romanji:"chuui", japanese:"ちゅうい", answer:"attention, caution" },
  { romanji:"chuusha", japanese:"ちゅうしゃ", answer:"parking; injection" },
  { romanji:"chuushajou", japanese:"ちゅうしゃじょう", answer:"parking lot" },

  { romanji:"daaku", japanese:"ダーク", answer:"dark" },
  { romanji:"daijina", japanese:"だいじな", answer:"important" },
  { romanji:"daiji", japanese:"だいじ", answer:"important" },
  { romanji:"daijin", japanese:"だいじん", answer:"minister" },

  { romanji:"daikirai", japanese:"だいきらい", answer:"hate (strong)" },
  { romanji:"daisuki", japanese:"だいすき", answer:"love, really like" },

  { romanji:"danshi", japanese:"だんし", answer:"boy, male" },
  { romanji:"danshi-sei", japanese:"だんしせい", answer:"male student" },
  { romanji:"dansou", japanese:"だんそう", answer:"generation gap" },

  { romanji:"dekakeru", japanese:"でかける", answer:"to go out" },
  { romanji:"dekiru", japanese:"できる", answer:"can do; be able to" },
  { romanji:"demasu", japanese:"でます", answer:"to go out; to leave" },

  { romanji:"denshi", japanese:"でんし", answer:"electronic" },
  { romanji:"denshi-jisho", japanese:"でんしじしょ", answer:"electronic dictionary" },

  { romanji:"doro", japanese:"どろ", answer:"mud" },
  { romanji:"dorobou", japanese:"どろぼう", answer:"thief" },

  { romanji:"dougu", japanese:"どうぐ", answer:"tool" },
  { romanji:"douka", japanese:"どうか", answer:"please" },
  { romanji:"douji", japanese:"どうじ", answer:"same time" },
  { romanji:"douka-shiteiru", japanese:"どうかしている", answer:"crazy, weird" }
];


const japaneseWordsN4_Part9 = [
  // E
  { romanji:"eki", japanese:"えき", answer:"station" },
  { romanji:"egao", japanese:"えがお", answer:"smiling face" },
  { romanji:"eru", japanese:"える", answer:"to get, obtain" },
  { romanji:"en", japanese:"えん", answer:"yen; circle" },
  { romanji:"enjin", japanese:"エンジン", answer:"engine" },
  { romanji:"enshutsu", japanese:"えんしゅつ", answer:"performance, production" },

  // F
  { romanji:"fuben", japanese:"ふべん", answer:"inconvenient" },
  { romanji:"futsuu", japanese:"ふつう", answer:"normal, usual" },
  { romanji:"futsuka", japanese:"ふつか", answer:"the second day of the month" },
  { romanji:"fuyu", japanese:"ふゆ", answer:"winter" },
  { romanji:"futoi", japanese:"ふとい", answer:"thick, fat" },
  { romanji:"futago", japanese:"ふたご", answer:"twins" },
  { romanji:"futon", japanese:"ふとん", answer:"Japanese bedding" },
  { romanji:"furo", japanese:"ふろ", answer:"bath" },
  { romanji:"fureai", japanese:"ふれあい", answer:"interaction, contact" },
  { romanji:"fun", japanese:"ふん", answer:"minute (time)" },
  { romanji:"fune", japanese:"ふね", answer:"ship, boat" },
  { romanji:"fushigi", japanese:"ふしぎ", answer:"mysterious, wonder" },
  { romanji:"futsukayoi", japanese:"ふつかよい", answer:"hangover" }
];


const japaneseWordsN4_Part10 = [
  // G
  { romanji:"gakkou", japanese:"がっこう", answer:"school" },
  { romanji:"gakusei", japanese:"がくせい", answer:"student" },
  { romanji:"gakkari", japanese:"がっかり", answer:"disappointment, feel let down" },
  { romanji:"gaman", japanese:"がまん", answer:"perseverance, patience" },
  { romanji:"gomi", japanese:"ごみ", answer:"trash, garbage" },
  { romanji:"gohan", japanese:"ごはん", answer:"rice; meal" },
  { romanji:"gojuu", japanese:"ごじゅう", answer:"fifty" },
  { romanji:"gozen", japanese:"ごぜん", answer:"a.m.; morning" },

  // H
  { romanji:"hajimeru", japanese:"はじめる", answer:"to start, begin (transitive)" },
  { romanji:"hajimaru", japanese:"はじまる", answer:"to begin (intransitive)" },
  { romanji:"hajimete", japanese:"はじめて", answer:"for the first time" },
  { romanji:"han", japanese:"はん", answer:"half" },
  { romanji:"hanasu", japanese:"はなす", answer:"to speak, talk" },
  { romanji:"hana", japanese:"はな", answer:"flower" },
  { romanji:"hanashi", japanese:"はなし", answer:"story, talk" },
  { romanji:"hanbun", japanese:"はんぶん", answer:"half" },
  { romanji:"hataraku", japanese:"はたらく", answer:"to work" },
  { romanji:"hentai", japanese:"へんたい", answer:"pervert; unusual" },
  { romanji:"heya", japanese:"へや", answer:"room" },
  { romanji:"hidoi", japanese:"ひどい", answer:"terrible, awful" },
  { romanji:"hitori", japanese:"ひとり", answer:"one person, alone" },
  { romanji:"hontou", japanese:"ほんとう", answer:"truth, really" },
  { romanji:"hon", japanese:"ほん", answer:"book" },
  { romanji:"honya", japanese:"ほんや", answer:"bookstore" },
  { romanji:"hiyake", japanese:"ひやけ", answer:"sunburn" },
  { romanji:"hisa", japanese:"ひさ", answer:"long time" }
];


const japaneseWordsN4_Part11 = [
  // I
  { romanji:"ii", japanese:"いい", answer:"good" },
  { romanji:"iie", japanese:"いいえ", answer:"no" },
  { romanji:"ikimasu", japanese:"いきます", answer:"to go" },
  { romanji:"iku", japanese:"いく", answer:"to go" },
  { romanji:"imooto", japanese:"いもうと", answer:"younger sister" },
  { romanji:"ire", japanese:"いれ", answer:"put in" },

  // J
  { romanji:"jikan", japanese:"じかん", answer:"time, hour" },
  { romanji:"jibun", japanese:"じぶん", answer:"oneself" },
  { romanji:"jidousha", japanese:"じどうしゃ", answer:"car" },
  { romanji:"juu", japanese:"じゅう", answer:"ten" },
  { romanji:"juugyou", japanese:"じゅぎょう", answer:"class, lesson" },
  { romanji:"juusho", japanese:"じゅうしょ", answer:"address" },

  // K
  { romanji:"kaeru", japanese:"かえる", answer:"to return home" },
  { romanji:"kaesu", japanese:"かえす", answer:"to return (something)" },
  { romanji:"kasa", japanese:"かさ", answer:"umbrella" },
  { romanji:"katana", japanese:"かたな", answer:"sword" },
  { romanji:"kawaii", japanese:"かわいい", answer:"cute" },
  { romanji:"kaze", japanese:"かぜ", answer:"wind; cold (illness)" },
  { romanji:"kekkon", japanese:"けっこん", answer:"marriage" },
  { romanji:"kiku", japanese:"きく", answer:"to listen; to ask" },
  { romanji:"kirei", japanese:"きれい", answer:"beautiful, clean" },

  // L
  { romanji:"rajio", japanese:"ラジオ", answer:"radio" },

  // M
  { romanji:"magaru", japanese:"まがる", answer:"to turn" },
  { romanji:"mae", japanese:"まえ", answer:"front, before" },
  { romanji:"machi", japanese:"まち", answer:"town" },
  { romanji:"mado", japanese:"まど", answer:"window" },
  { romanji:"maji", japanese:"まじ", answer:"seriously" },
  { romanji:"manabu", japanese:"まなぶ", answer:"to study" },
  { romanji:"miru", japanese:"みる", answer:"to see, look, watch" },
  { romanji:"minna", japanese:"みんな", answer:"everyone" },

  // N
  { romanji:"namae", japanese:"なまえ", answer:"name" },
  { romanji:"naka", japanese:"なか", answer:"inside" },
  { romanji:"naka-yoku", japanese:"なかよく", answer:"on good terms" },
  { romanji:"nani", japanese:"なに", answer:"what" },
  { romanji:"nanika", japanese:"なにか", answer:"something" },
  { romanji:"neru", japanese:"ねる", answer:"to sleep" },
  { romanji:"noru", japanese:"のる", answer:"to ride" },

  // O
  { romanji:"oishii", japanese:"おいしい", answer:"delicious" },
  { romanji:"okiru", japanese:"おきる", answer:"to get up" },
  { romanji:"okuru", japanese:"おくる", answer:"to send" },
  { romanji:"omoi", japanese:"おもい", answer:"heavy" },
  { romanji:"omou", japanese:"おもう", answer:"to think" },
  { romanji:"onna", japanese:"おんな", answer:"woman" },

  // P
  { romanji:"paatii", japanese:"パーティー", answer:"party" },
  { romanji:"pan", japanese:"パン", answer:"bread" },
  { romanji:"petto", japanese:"ペット", answer:"pet" },

  // R
  { romanji:"raku", japanese:"らく", answer:"comfortable, easy" },
  { romanji:"ramen", japanese:"ラーメン", answer:"ramen" },
  { romanji:"ryokou", japanese:"りょこう", answer:"travel, trip" },
  { romanji:"ryouri", japanese:"りょうり", answer:"cooking, cuisine" },

  // S
  { romanji:"sakura", japanese:"さくら", answer:"cherry blossom" },
  { romanji:"sanpo", japanese:"さんぽ", answer:"walk, stroll" },
  { romanji:"shigoto", japanese:"しごと", answer:"work, job" },
  { romanji:"shinkansen", japanese:"しんかんせん", answer:"bullet train" },
  { romanji:"shizuka", japanese:"しずか", answer:"quiet" },
  { romanji:"soba", japanese:"そば", answer:"near, beside; buckwheat noodles" },

  // T
  { romanji:"tabemono", japanese:"たべもの", answer:"food" },
  { romanji:"taberu", japanese:"たべる", answer:"to eat" },
  { romanji:"tokei", japanese:"とけい", answer:"watch, clock" },
  { romanji:"tomodachi", japanese:"ともだち", answer:"friend" },
  { romanji:"tsukue", japanese:"つくえ", answer:"desk" },
  { romanji:"tsukuru", japanese:"つくる", answer:"to make, create" },

  // U
  { romanji:"umai", japanese:"うまい", answer:"delicious, skillful" },
  { romanji:"umi", japanese:"うみ", answer:"sea, ocean" },
  { romanji:"usui", japanese:"うすい", answer:"thin, weak" },
  { romanji:"utau", japanese:"うたう", answer:"to sing" },

  // W
  { romanji:"watashi", japanese:"わたし", answer:"I, me" },
  { romanji:"wakareru", japanese:"わかれる", answer:"to separate, part" },
  { romanji:"wakaru", japanese:"わかる", answer:"to understand" },

  // Y
  { romanji:"yama", japanese:"やま", answer:"mountain" },
  { romanji:"yasai", japanese:"やさい", answer:"vegetables" },
  { romanji:"yasumu", japanese:"やすむ", answer:"to rest, be absent" },
  { romanji:"yomu", japanese:"よむ", answer:"to read" },
  { romanji:"yoroshiku", japanese:"よろしく", answer:"please treat me well" },

  // Z
  { romanji:"zasshi", japanese:"ざっし", answer:"magazine" },
  { romanji:"zettai", japanese:"ぜったい", answer:"absolutely, definitely" },
  { romanji:"zutto", japanese:"ずっと", answer:"continuously, all the time" }
];





const japaneseWords = [
  ...japaneseWords1,
  ...japaneseWordsPart2,
  ...japaneseWordsPart3,
  ...japaneseWordsPart4,
  ...japaneseWordsN4_Part5,
  ...japaneseWordsN4_Part6,
  ...japaneseWordsN4_Part7,
  ...japaneseWordsN4_Part8,
  ...japaneseWordsN4_Part9,
  ...japaneseWordsN4_Part10,
  ...japaneseWordsN4_Part11
];
export default japaneseWords;